config/routes.rb
Sin::Application.routes.draw do

  root :to => 'application#index'

  match '/support' => 'support#index', :as => :support
  match '/logout' => 'sin#logout', :as => :logout
  match '/logo' => 'sin#logo', :as => :logo
  match '/session_expired' => 'sin#session_expired', :as => :session_expired
  match '/login_text' => 'sin#login_text', :as => :login_text

  resources :password_resets, :except => [:index, :destroy]
  resources :roles
  resources :service_providers

  resources :schedules do
    member do
      post   :generate
      get    :reports
      delete :destroy_report
    end
  end  

  resources :settings do
    collection do
      post :update
      get :edit
    end
  end

  resources :users do
    put :set_homepage
    put :toggle_table
    resources :filter_templates, :only => [:create, :update, :destroy]
    resources :site_lists, :only => [:create, :update, :destroy]
  end

  resource :dashboard, :only => [:index] do
    get :index
    get :inventory
    get :ordering
    get :monitoring
    resources :event, :controller => :dashboards, :only => :show do
      collection do
        post :data
      end
    end
  end
  
  resource :report, :only => [:index] do
    get :index    
    get :paths

    get :sla
    get :site_group
    get :satellite_site
    get :cell_site
    get :cell_site_path
    get :metrics
    get :oem_sla
    get :fallout_exception
    get :circuit_utilization
    get :enni_utilization
    
    # required for datatables
    post :sla
    post :site_group
    post :satellite_site
    post :cell_site
    post :cell_site_path
    post :metrics
    post :oem_sla
    post :circuit_utilization
    post :enni_utilization
    post :paths
  end
  
  resources :member_handle_instances do
    collection do
      post :create_or_update
    end
  end

  def standard_component_routes
    member do
      get :ordering
      get :ordering_state
      get :ordering_state_edit
      get :ordering_attributes
      get :ordering_output
      get :ordering_audit
      put :ordering_field_update
      put :provisioning_state_update
      get :monitoring
      get :sm_state
      get :event_history
      get :availability_graph
      get :delay_graph
      get :delay_variation_graph
      get :frame_loss_ratio_graph
      get :troubleshooting_graph
    end
  end

  # Map network on map (agg sites and demarcs)
  resources :network do
    collection do 
      get :demarcs_by_site
    end
  end

  resources :monitoring

  resources :service_orders, :only => [:update]
  match 'service_orders/:id/place_order/:path_id', :to => 'service_orders#place_order', :via => [:post], :as => "place_service_order"
  match 'service_orders/screenshot/:cascade/:order_type/:ts/:num.png', :to => 'service_orders#screenshot', :as => "service_order_screenshot"

  resources :paths do
    standard_component_routes
    member do
      get :list_row
      get :revision
      get :view_data_sources
    end  
  end

  resources :cos_test_vectors do
    member do
      get :availability_graph
      get :delay_graph
      get :delay_variation_graph
      get :frame_loss_ratio_graph
      get :troubleshooting_graph
      get :network_monitoring
    end    
  end

  resources :off_net_ovcs do
    standard_component_routes
    collection do 
      get :map_info_window
      get :map_tooltip
    end
  end

  resources :on_net_ovcs do
    standard_component_routes
    member do
      get :genconfig
      get :site
    end   
    collection do 
      get :map_info_window
      get :map_tooltip
    end     
  end

  resources :nodes do
    member do
      put :provisioning_state_update
    end
    collection do 
      get :nodes
    end
  end

  resources :on_net_routers do
    standard_component_routes
    member do
      get :genconfig
      get :nodes
      get :site
    end   
    collection do 
      get :map_info_window
    end     
  end

  resources :sites do
    member do 
      get :map_info_window
    end
  end

  resources :demarcs do
    standard_component_routes
    collection do 
      get :map_info_window
      get :map_tooltip
    end
  end

  resources :ennis do
    standard_component_routes
    member do
      get :list_row
    end
  end

  resources :off_net_ovc_end_point_unis do
    standard_component_routes
  end

  resources :off_net_ovc_end_point_ennis do
    standard_component_routes
  end

  resources :on_net_ovc_end_point_ennis do
    standard_component_routes
  end

  resources :on_net_router_sub_ifs do
    standard_component_routes
  end

  resources :path_displays do
    member do
      get :monitoring_view
      get :ordering_state_view
      get :inventory_state_view
      get :monitoring_state_view
      get :demarc_view
      get :circuit_path_view
      get :bandwidth_view
      get :technical_contacts_view
      get :summary_view
    end
  end

  resources :enni_displays do
    member do
      get :ordering_state_view
      get :inventory_state_view
      get :monitoring_state_view
      get :technical_contacts_view
    end
  end
  
  resources :state

  # Compare graphs side-by-side
  resources :compares do
    collection do
      delete :clear
      put :reorder
    end
  end


  # Coresite Orders and Tenants
  resources :coresite_orders do
    member do 
      get :change
      put :process_change
      put :accept
      put :update
      put :reject
      put :cancel
      delete :disconnect
      get :_check_available_bandwidth
      get :_view_build_log
    end
    collection do
      get :_check_available_bandwidth_and_vlan
      get :_sites_select
      get :_operator_networks_select
      get :_ennis_select
      get :_phy_type
      get :_access_permission
      get :_provisioned_bandwidth
      get :_next_available_vlan
      get :_service_rates_select
      get :_contact
    end
  end

  resources :custom_application do
    collection do
      get :_locations
      get :_show_add_port
      get :_show_edit_port
      get :_show_delete_port
      get :_nodes_select
      post :_create_port
      put :_update_port
      put :_delete_port
      post :upload_tenants
      get :import_tenants
      get :access_permissions
      put :_update_access_permissions
    end
  end
  
end

app/models/cdb/schedule.rb
class Schedule< ActiveRecord::Base
  after_save :update_crontab
  before_create :general_before_create  
  before_destroy :general_before_destroy
  
  belongs_to :scheduled_task
  has_many :reports, :order => "created_at DESC", :dependent => :destroy
  store :formats
  
  validates_uniqueness_of :name
  validates :name, :retention_time, :scheduled_task, :trigger, :timezone, :presence => true
  validates_associated :scheduled_task
  validates :trigger, :inclusion => { :in => %w(daily weekly monthly yearly), :message => "value is not supported"}
  validate :validate_email_options

  CRONTAB_PREFIX = "ScheduledReport_"
  CRON_LOG_DIR = "#{Rails.root}/log/cron/"
  
  def self.for_user(user)
    self.includes({:scheduled_task => :user}, :reports).where('scheduled_tasks.user_id = ?', user.id)
  end
  
  def general_before_create
    if formats.blank?
      self.formats = scheduled_task.supported_attachemts
    end
    true
  end
  
  def general_before_destroy
    CronEdit::Crontab.Remove(CRONTAB_PREFIX + self.name)
    true
  end
  
  def update_reports
    reports.each {|rep| rep.update_report}
    true
  end
  
  def formats_sentence
    self.formats.map { |k,v| 
      if v 
        if k.length > 3 
          k.titleize 
        else
          k.upcase
        end
      end
    }.compact.to_sentence
  end

  def self.remove_old_reports
    Schedule.all.each do |sr|
      # remove any old records
      if sr.retention_time != 0
        # Don't delete the last one as we want to guarantee there will always be history for the retention time as it's used to calculate
        # availability so a record is needed that is at least retention_time old
        reports = sr.reports.where("run_date < ?", (Time.now-sr.retention_time.days))
        reports.each {|report| report.destroy}
      end
    end
  end
  
  # If databases are deleted/added then the crontab won't match so need to resync crontab with the database
  def self.resync_crontab
    current_crontab = CronEdit::Crontab.List.keys
    # Remove any that don't have a key starting with CRONTAB_PREFIX - This is because "whenever" gem uses ##__nnnn__## as a name so Crontab.List returns
    # those entries as well
    current_crontab.delete_if {|name| name[/^#{CRONTAB_PREFIX}/] == nil}
    database_crontab = Schedule.pluck(:name)
    # Add the prefix to the names in the database
    database_crontab.collect! {|name| CRONTAB_PREFIX + name}
    to_delete = current_crontab-database_crontab
    
    cm = CronEdit::Crontab.new 
    to_delete.each {|name| cm.remove(name)}  
    Schedule.find_each {|sr| sr.make_crontab(cm)}      
    cm.commit
  end

  
  def run_now
    system(make_cmd)
  end

  def update_crontab    
    if enabled_changed? || execution_time_changed? || trigger_changed? || timezone_changed? || execution_time.utc < Time.now.utc
      cm = CronEdit::Crontab.new 
      make_crontab(cm)
      cm.commit
    end
    return true
  end
  
  def make_crontab(cron_list)
    # '07 14 15 3 3 /bin/bash -l -c \'cd /Users/bwessels/oss-db_kpi/ && bundle exec rails runner "File.open(\"/Users/bwessels/bjw_test1.txt\", \"w+\")"\''
    cron_entry = format_crontab_time + " " + make_cmd 
    if enabled
      cron_list.add(CRONTAB_PREFIX + name, cron_entry)
    else
      cron_list.remove(CRONTAB_PREFIX + name)
    end
    return cron_list
  end
  
  private
  
  def enabled_or_execution_time_changed
    enabled || execution_time
  end
    
  def validate_email_options
    if email_distribution
      if [email_to.blank?, email_cc.blank?, email_bcc.blank?].all?
        errors.add(:base, "There must be at least one email address provided")
      end
    end
  end

  def format_crontab_time
    # crontab format: Minute Hour Day_of_Month Month Day_of_Week
    utc_execution_time = execution_time.utc 
    if utc_execution_time > Time.now.utc
      # If the execution time is in the future set the first cron run time to be at that absolute time
      # After the first run the crontab entry will be updated to be periodic based on the trigger
      return "#{utc_execution_time.min} #{utc_execution_time.hour} #{utc_execution_time.day} #{utc_execution_time.month} *"
    end
    
    # Calculate the dst offset between now and the configured execution time then adjust the time
    dst_offset = execution_time.in_time_zone(timezone).utc_offset - Time.now.in_time_zone(timezone).utc_offset
    utc_execution_time = execution_time.utc + dst_offset
    min = utc_execution_time.min
    hour = utc_execution_time.hour
    
    case trigger
    when "monthly"
      "#{min} #{hour} #{utc_execution_time.day} * *"
    when "weekly"
      "#{min} #{hour} * * #{utc_execution_time.wday}"
    when "daily"
      "#{min} #{hour} * * *"
    when "yearly"
      "#{min} #{hour} #{utc_execution_time.day} #{utc_execution_time.month} *"
    else
      SW_ERR "Invalid trigger #{trigger}"
      nil
    end
  end
  
  def self.preamble_cron_script(sched_id)
    sched = Schedule.find(sched_id)
    Time.zone = sched.timezone
    result = "Schedule Time: #{Time.now.in_time_zone(sched.timezone)} #{sched.timezone} #{Time.zone}"
    puts result
    sched.update_crontab
  end
  
  def make_cmd
    rails_cmd = "\"Schedule.preamble_cron_script(#{self.id});" + scheduled_task.executable_script.gsub(/%SR_ID%/,self.id.to_s) + "\""
    if Rails.env == 'production'
      cmd = 'nice -n 15 /bin/bash -l -c ' + "\'export TZ=\"#{timezone}\" && #{scheduled_task.get_env_script} bundle exec rails runner #{rails_cmd}\'"
    else
      Dir::mkdir(CRON_LOG_DIR) unless File.exists?(CRON_LOG_DIR)
      cron_log_file = CRON_LOG_DIR + "#{name}.log".gsub(/ /, "_")
      cmd = 'nice -n 15 /bin/bash -l -c ' + "\'export TZ=\"#{timezone}\" && cd #{Rails.root} && bundle exec rails runner #{rails_cmd} >> #{cron_log_file} 2>&1\'"
    end
    return cmd
  end
    
end
# == Schema Information
#
# Table name: schedules
#
#  id                 :integer(4)      not null, primary key
#  name               :string(255)     not null
#  scheduled_task_id  :integer(4)
#  exclusion_list_id  :integer(4)
#  enabled            :boolean(1)
#  trigger            :string(255)
#  formats            :text
#  last_run           :datetime
#  retention_time     :integer(4)
#  execution_time     :datetime
#  email_distribution :boolean(1)
#  email_to           :string(255)
#  email_cc           :string(255)
#  email_bcc          :string(255)
#  email_subject      :string(255)
#  email_body         :string(255)
#  created_at         :datetime        not null
#  updated_at         :datetime        not null
#  timezone           :string(255)
#

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  load_and_authorize_resource
  before_filter do |c| @reports_page = true end
  before_filter :find_schedule, :except => [:index, :new, :create]
  before_filter :set_default_params, :only => [:edit, :update, :create]

  # GET /schedules
  # GET /schedules.json
  def index
    if @current_user.system_admin?
      @schedules = Schedule.includes({:scheduled_task => :user}, :reports).where('scheduled_tasks.user_id IS NOT NULL')
    else
      @schedules = Schedule.for_user(@current_user)
    end
    @filters = FilterTemplate.all_filters(@current_user)  

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @schedules }
    end
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @schedule }
    end
  end

  # GET /schedules/new
  # GET /schedules/new.json
  def new
    @schedule = Schedule.new
    @schedule.execution_time = DateTime.parse("00:00") 
    @schedule.enabled = true
    @schedule.email_distribution = true
    @schedule.trigger = 'weekly'
    @schedule.formats[:web_link] = true
    @user = @current_user
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @schedule }
    end
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(params[:schedule])
    @user = @schedule.scheduled_task.user
    
    respond_to do |format|
      if @schedule.save
        format.html { redirect_to schedules_path, notice: "Report #{@schedule.name} has been scheduled." }
        format.json { render json: @schedule, status: :created, location: @schedule }
      else
        format.html { render action: "new" }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schedules/1
  # PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update_attributes(params[:schedule])
        format.html { redirect_to schedules_url, notice: 'Scheduled report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy

    respond_to do |format|
      format.html { redirect_to schedules_url }
      format.json { head :no_content }
    end
  end
  
  def generate
    report = @schedule.scheduled_task.generate_report(params[:id])
    report.run_manually = true
    respond_to do |format|
      if report.save
        format.html { redirect_to reports_schedule_path(@schedule), :notice => "#{@schedule.name} report has been successfully generated." }
        format.json { head :no_content }
      else
        format.html { redirect_to reports_schedule_path(@schedule), :alert => "#{@schedule.name} report could not be generated." }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def reports
    @reports = @schedule.reports.order('created_at DESC')
    respond_to do |format|
      format.html # reports.html.erb
      format.json { render json: @schedule.reports }
    end    
  end
  
  def destroy_report
    @schedule.reports.find(params[:report_id]).destroy

    respond_to do |format|
      format.html { redirect_to reports_schedule_path(@schedule) }
      format.json { head :no_content }
    end  
  end
  
  private
  
  def find_schedule
    if @current_user.system_admin?
      @schedule = Schedule.find(params[:id])
    else
      @schedule = Schedule.for_user(@current_user).where('schedules.id = ?', params[:id]).first
    end

    @user = @schedule.scheduled_task.user
  end

  def set_default_params
    Time.zone = @schedule.timezone

    if params[:schedule].present?
      if params[:schedule][:formats].blank?
        params[:schedule][:formats] = {}
      end

      [:web_link, :csv, :pdf].each do |format|
        params[:schedule][:formats][format] ||= false
      end
    end
  end
end

app/views/schedules/_form.html.haml
=form_for(@schedule) do |f| 
  -if @schedule.errors.any?
    #error_explanation
      %a.close{'data-dismiss' => 'alert'} 
        ×
        
      %h2
        =pluralize(@schedule.errors.count, "error")
        prohibited this user from being saved

      %ul
        -@schedule.errors.full_messages.each do |msg|
          %li
            =msg.gsub('Trigger', 'Report Schedule')
 
  .grid_4.alpha

    =f.check_box :enabled
    =f.label :enabled, 'Report Enabled', {:style => 'display:inline'}

    %br.clear
    %br.clear

    %label
      Title
    =f.text_field :name

    %label
      Filter

    -filters = FilterTemplate.all_filters(@user)  
    -if filters.empty?
      %p
        %em
          A filter is required. Please 
          =link_to "create one first →", report_path
    -else
      =f.collection_select :scheduled_task_id, filters, :id, :display_name
  
    %label
      Report Schedule
      
    =f.radio_button :trigger, 'daily'
    Daily

    &nbsp;
    =f.radio_button :trigger, 'weekly'
    Weekly

    &nbsp;
    =f.radio_button :trigger, 'monthly'
    Monthly

    &nbsp;
    =f.radio_button :trigger, 'yearly'
    Yearly
    
    %br.clear
    %br.clear
    
    %label
      Start Date
    
    =text_field nil, nil, :autocomplete => 'off', :class => 'start_date', :value => @schedule.execution_time.strftime('%Y-%m-%d')

    %label
      Execution Time
    
    .time_select  
      =f.time_select :execution_time

    %label
      Execution Time Zone
    
    =f.time_zone_select :timezone, ActiveSupport::TimeZone.us_zones, :default => "Eastern Time (US & Canada)"


    %label
      Retention Time

    =f.number_field :retention_time, {:min => 1, :width => 3, :value => 365}
    days    
    
    
      
  .grid_7.alpha.omega
    
    =f.check_box :email_distribution
    =f.label :email_distribution, 'Distribute Report', {:style => 'display:inline'}
      
      
    %br.clear  
    %br.clear
    
    .grid_4.alpha.omega

      .distribution_fields
        %label
          Email To
        =f.text_field :email_to

        %label
          CC
        =f.text_field :email_cc

        %label
          Subject
        =f.text_field :email_subject

        %label
          Format

        =check_box_tag "schedule[formats][web_link]", true, @schedule.formats[:web_link]
        Web link
        
        =check_box_tag "schedule[formats][csv]", true, @schedule.formats[:csv]
        CSV

        =check_box_tag "schedule[formats][pdf]", true, @schedule.formats[:pdf]
        PDF

        
    .grid_3.alpha.omega
      .distribution_fields
        %label
          Body
        =f.text_area :email_body, :rows => 11
    
      %br.clear
      =f.submit(:class => 'submit_button', :value => @schedule.new_record? ? 'Create' : 'Update')
      or 
      =link_to 'Cancel', schedules_path
                
    

app/views/schedules/edit.html.haml
-content_for :title do
  CENX - Edit Scheduled Report

.container_12
  .border.clearfix
    .grid_9.alpha
      %h1
        %a{:href => schedules_path}
          Scheduled Reports
        ="/ Edit #{@schedule.name}"
        

    .grid_3.align_right.service_provider_logo.omega
      =provider_logo(@current_user.service_provider)


.container_12
  .grid_12.alpha.omega
    = render :partial => 'form'
    
.clear
%br

app/views/schedules/index.html.haml
-content_for :title do
  CENX - Scheduled Reports

.container_12
  .border.clearfix
    .grid_9.alpha
      %h1
        Scheduled Reports

    .grid_3.align_right.service_provider_logo.omega
      =provider_logo(@current_user.service_provider)


.container_12
  .grid_12.alpha.omega
  
    =render :partial => 'shared/flash_message'
  
    .right
      -if @filters.empty?
        %a.submit_button.icon.clock{:href => '#', :class => 'disabled help_on_hover', :title => 'A filter is required to schedule a report'}
          Schedule a Report
      -else
        %a.submit_button.icon.clock{:href => new_schedule_path}
          Schedule a Report
  
    %h3.inline
      &nbsp;

    %table.dashboard_table.schedules_table
      %thead
        %tr
          %th Title
          %th Filter
          -if @current_user.system_admin?
            %th Owner
          %th Schedule
          %th Enabled
          %th Reports
          %th Format
          %th Last Run
          %th 
                                                
      %tbody
        -@schedules.each do |sr|
          %tr
            %td
              = link_to sr.name, reports_schedule_path(sr)
            %td
              = link_to sr.scheduled_task.name, filter_template_url(sr.scheduled_task)
            -if @current_user.system_admin?
              %td
                =link_to sr.scheduled_task.user.display_name, edit_user_path(sr.scheduled_task.user)
            %td
              = sr.trigger.titleize
            %td
              = yes_no sr.enabled
            %td
              = link_to sr.reports.length, reports_schedule_path(sr)
            %td
              = sr.formats_sentence
            %td
              -if sr.last_run
                =sr.last_run.in_time_zone(sr.timezone)
              -else
                Not yet run
                %br
                
            %td.align_right.no_wrap
              .button-group.small
                = link_to "Run Report", generate_schedule_path(sr), :method => :post, :class => 'submit_button icon log activity', :title => "Run this report now", :confirm => 'Generating a Report can take several minutes. Do you want to proceed?'
                = link_to 'Edit', edit_schedule_path(sr), class: 'submit_button icon edit', :title => "Edit #{sr.name}"
                = link_to 'Remove', sr, confirm: "Are you sure you want to remove #{sr.name}?", method: :delete, class: 'submit_button icon remove negative', title: "Remove #{sr.name}"

app/views/schedules/new.html.haml
-content_for :title do
  CENX - New Scheduled Report

.container_12
  .border.clearfix
    .grid_9.alpha
      %h1
        %a{:href => schedules_path}
          Scheduled Reports
        ="/ "
        New Scheduled Report

    .grid_3.align_right.service_provider_logo.omega
      =provider_logo(@current_user.service_provider)


.container_12
  .grid_12.alpha.omega
    = render :partial => 'form'
    
.clear
%br

app/views/schedules/reports.html.haml
-content_for :title do
  CENX - Scheduled Reports

.container_12
  .border.clearfix
    .grid_9.alpha
      %h1
        %a{:href => schedules_path}
          Scheduled Reports
        ="/ "
        Reports

    .grid_3.align_right.service_provider_logo.omega
      =provider_logo(@current_user.service_provider)


.container_12
  .grid_12.alpha.omega
  
    =render :partial => 'shared/flash_message'
  
    .right
      = link_to "Run Report Now", generate_schedule_path(@schedule), :method => :post, :class => 'submit_button icon log activity', :confirm => 'Generating a Report can take several minutes. Do you want to proceed?'
  
    %h3.inline
      =@schedule.name
      Reports

    %table.dashboard_table.reports_table
      %thead
        %tr
          %th Results
          %th Report Generated 
          %th Date
          %th

      %tbody
        -@reports.each do |r|
          %tr
            %td
              -if r.is_a?(MetricsReport) || r.is_a?(CellSitePathReport) || r.is_a?(CellSiteReport) || r.is_a?(SatelliteSiteReport) || r.is_a?(SiteGroupReport)
                =dashboard_pie(:title => '',
                               :data => [r.clear_exceptions, r.minor_exceptions, r.major_exceptions],
                               :labels => ['OK', 'Minor', 'Major'], 
                               :bar_colors => ['609C25', 'FF8D20', 'ba2a2a'],
                               :links => [filter_template_url(r.scheduled_task),
                                          filter_template_url(r.scheduled_task),
                                          filter_template_url(r.scheduled_task), 
                                          ],
                               :width => 175, 
                               :height => 50,
                               :tooltip => 'none')
              -else
                -if r.minor_exceptions == 0 && r.major_exceptions == 0 && r.critical_exceptions == 0
                  =dashboard_pie(:title => '',
                                 :data => [1],
                                 :labels => ['OK'], 
                                 :bar_colors => ['609c25'],
                                 :links => [filter_template_url(r.scheduled_task)],
                                 :width => 175, 
                                 :height => 50,
                                 :tooltip => 'none')

                -else
                  =dashboard_pie(:title => '',
                                 :data => [r.minor_exceptions, r.major_exceptions, r.critical_exceptions],
                                 :labels => ['Minor', 'Major', 'Critical'], 
                                 :bar_colors => ['DCDE32', 'FF8D20', 'ba2a2a'],
                                 :links => [filter_template_url(r.scheduled_task),
                                            filter_template_url(r.scheduled_task), 
                                            filter_template_url(r.scheduled_task)],
                                 :width => 175, 
                                 :height => 50,
                                 :tooltip => 'none')
            %td
              ="#{r.run_manually? ? 'Manual' : 'Scheduled'}" 
            %td
              =r.run_date.in_time_zone(@schedule.timezone)

            %td.align_right.no_wrap
              .button-group.small
                = link_to 'View', filter_template_url(r.scheduled_task), class: 'submit_button icon arrowright', title: "View #{@schedule.name} Report"
                = link_to 'Remove', destroy_report_schedule_path(r.schedule, :report_id => r.id), confirm: "Are you sure you want to remove this report?", method: :delete, class: 'submit_button icon remove negative', title: "Remove Report"
              