config/routes.rb
Sin::Application.routes.draw do

  root :to => 'application#index'

  match '/support' => 'support#index', :as => :support
  match '/logout' => 'sin#logout', :as => :logout
  match '/logo' => 'sin#logo', :as => :logo
  match '/session_expired' => 'sin#session_expired', :as => :session_expired
  match '/login_text' => 'sin#login_text', :as => :login_text

  resources :password_resets, :except => [:index, :destroy]
  resources :roles
  resources :service_providers

  resources :schedules do
    member do
      post   :generate
      get    :reports
      delete :destroy_report
    end
  end  

  resources :settings do
    collection do
      post :update
      get :edit
    end
  end

  resources :users do
    put :set_homepage
    put :toggle_table
    resources :filter_templates, :only => [:create, :update, :destroy]
    resources :site_lists, :only => [:create, :update, :destroy]
  end

  resource :dashboard, :only => [:index] do
    get :index
    get :inventory
    get :ordering
    get :monitoring
    resources :event, :controller => :dashboards, :only => :show do
      collection do
        post :data
      end
    end
  end
  
  resource :report, :only => [:index] do
    get :index    
    get :paths

    get :sla
    get :site_group
    get :satellite_site
    get :cell_site
    get :cell_site_path
    get :metrics
    get :oem_sla
    get :fallout_exception
    get :circuit_utilization
    get :enni_utilization
    
    # required for datatables
    post :sla
    post :site_group
    post :satellite_site
    post :cell_site
    post :cell_site_path
    post :metrics
    post :oem_sla
    post :circuit_utilization
    post :enni_utilization
    post :paths
  end
  
  resources :member_handle_instances do
    collection do
      post :create_or_update
    end
  end

  def standard_component_routes
    member do
      get :ordering
      get :ordering_state
      get :ordering_state_edit
      get :ordering_attributes
      get :ordering_output
      get :ordering_audit
      put :ordering_field_update
      put :provisioning_state_update
      get :monitoring
      get :sm_state
      get :event_history
      get :availability_graph
      get :delay_graph
      get :delay_variation_graph
      get :frame_loss_ratio_graph
      get :troubleshooting_graph
    end
  end

  # Map network on map (agg sites and demarcs)
  resources :network do
    collection do 
      get :demarcs_by_site
    end
  end

  resources :monitoring

  resources :service_orders, :only => [:update]
  match 'service_orders/:id/place_order/:path_id', :to => 'service_orders#place_order', :via => [:post], :as => "place_service_order"
  match 'service_orders/screenshot/:cascade/:order_type/:ts/:num.png', :to => 'service_orders#screenshot', :as => "service_order_screenshot"

  resources :paths do
    standard_component_routes
    member do
      get :list_row
      get :revision
      get :view_data_sources
    end  
  end

  resources :cos_test_vectors do
    member do
      get :availability_graph
      get :delay_graph
      get :delay_variation_graph
      get :frame_loss_ratio_graph
      get :troubleshooting_graph
      get :network_monitoring
    end    
  end

  resources :off_net_ovcs do
    standard_component_routes
    collection do 
      get :map_info_window
      get :map_tooltip
    end
  end

  resources :on_net_ovcs do
    standard_component_routes
    member do
      get :genconfig
      get :site
    end   
    collection do 
      get :map_info_window
      get :map_tooltip
    end     
  end

  resources :nodes do
    member do
      put :provisioning_state_update
    end
    collection do 
      get :nodes
    end
  end

  resources :on_net_routers do
    standard_component_routes
    member do
      get :genconfig
      get :nodes
      get :site
    end   
    collection do 
      get :map_info_window
    end     
  end

  resources :sites do
    member do 
      get :map_info_window
    end
  end

  resources :demarcs do
    standard_component_routes
    collection do 
      get :map_info_window
      get :map_tooltip
    end
  end

  resources :ennis do
    standard_component_routes
    member do
      get :list_row
    end
  end

  resources :off_net_ovc_end_point_unis do
    standard_component_routes
  end

  resources :off_net_ovc_end_point_ennis do
    standard_component_routes
  end

  resources :on_net_ovc_end_point_ennis do
    standard_component_routes
  end

  resources :on_net_router_sub_ifs do
    standard_component_routes
  end

  resources :path_displays do
    member do
      get :monitoring_view
      get :ordering_state_view
      get :inventory_state_view
      get :monitoring_state_view
      get :demarc_view
      get :circuit_path_view
      get :bandwidth_view
      get :technical_contacts_view
      get :summary_view
    end
  end

  resources :enni_displays do
    member do
      get :ordering_state_view
      get :inventory_state_view
      get :monitoring_state_view
      get :technical_contacts_view
    end
  end
  
  resources :state

  # Compare graphs side-by-side
  resources :compares do
    collection do
      delete :clear
      put :reorder
    end
  end


  # Coresite Orders and Tenants
  resources :coresite_orders do
    member do 
      get :change
      put :process_change
      put :accept
      put :update
      put :reject
      put :cancel
      delete :disconnect
      get :_check_available_bandwidth
      get :_view_build_log
    end
    collection do
      get :_check_available_bandwidth_and_vlan
      get :_sites_select
      get :_operator_networks_select
      get :_ennis_select
      get :_phy_type
      get :_access_permission
      get :_provisioned_bandwidth
      get :_next_available_vlan
      get :_service_rates_select
      get :_contact
    end
  end

  resources :custom_application do
    collection do
      get :_locations
      get :_show_add_port
      get :_show_edit_port
      get :_show_delete_port
      get :_nodes_select
      post :_create_port
      put :_update_port
      put :_delete_port
      post :upload_tenants
      get :import_tenants
      get :access_permissions
      put :_update_access_permissions
    end
  end
  
end

app/models/cdb/service_provider.rb
# encoding: UTF-8
# == Schema Information
# Schema version: 20110802190849
#
# Table name: service_providers
#
#  id                       :integer(4)      not null, primary key
#  name                     :string(255)
#  website                  :string(255)
#  is_system_owner                  :boolean(1)
#  password_expiry_interval :integer(4)
#  created_at               :datetime
#  updated_at               :datetime
#  logo_url                 :string(255)
#  address                  :string(255)
#  cenx_cma                 :string(255)
#  cenx_id                  :string(255)
#  notes                    :string(255)
#

class ServiceProvider < ActiveRecord::Base
  include Kpiable
          
  has_many :users, :dependent => :destroy
  has_many :operator_networks, :order => "name", :dependent => :destroy
  has_many :operator_network_types, :order => "name", :dependent => :destroy
  has_many :enni_news, :through => :operator_networks
  has_many :ennis_on_behalf_of, :class_name => 'EnniNew', :foreign_key => :on_behalf_of_service_provider_id # Some Ennis were provisioned on behalf of this service provider
  has_many :demarcs, :through => :operator_networks
  has_many :paths, :through => :operator_networks
  has_many :contacts, :order => "name", :dependent => :destroy
  has_many :uploaded_files, :as => :uploader, :dependent => :destroy
  has_many :segments, :through => :operator_networks
  has_many :sin_path_service_provider_sphinxes
  has_many :sin_enni_service_provider_sphinxes
  store :terms, accessors: [ :network_type, :aggregation_site, :site, :wdc, :gateway_site, :demarc, :site_group, :service_provider, :path, :enni, :segment, :aav, :microwatt, :cascade ]

  validates_presence_of :name
  validates_uniqueness_of :name
  validates_as_cenx_id :cenx_id
  validate :valid_cenx_cma?

  after_save :set_path_sphinx_delta_flag
  after_create :general_after_create
  before_validation :generate_id_and_cma, :on => :create
  after_initialize :initialize_terms
  before_save :update_kpi_table, :if => :is_system_owner_changed?

  scope :real, :conditions => ["IFNULL(is_system_owner,0) = ?",false], :order => 'name ASC'

  attr_protected :is_system_owner, :is_system_logo

  def self.system_owner
    return find_by_is_system_owner(true)
  end
  
  def initialize_terms
    # Set the default terms
    self.path             ||= 'Path'
    self.enni             ||= 'ENNI'
    self.network_type     ||= 'Network Type'
    self.aggregation_site ||= 'Aggregation Site'
    self.site             ||= 'Site'
    self.wdc              ||= 'WDC'
    self.gateway_site     ||= 'CDC'
    self.demarc           ||= 'Demarc'
    self.site_group       ||= 'Site Group'
    self.service_provider ||= 'Service Provider'
    self.segment          ||= 'Segment'
    self.microwatt        ||= 'µW'
    self.aav              ||= 'AAV'
    self.cascade          ||= 'Cascade ID'
  end

  def general_after_create
    create_default_kpis
  end

  def self.find_rows_for_index
    order("name")
  end

  def self.system_admins
    where(:is_system_owner => true)
  end

  def self.set_system_logo(sp)
    self.transaction do
      self.update_all(:is_system_logo => false)
      sp.is_system_logo = true
      sp.save!
    end
  end

  def name_with_admin_label
    is_system_owner? ? "#{name} (System Owner)" : name
  end
  
  def really_cenx?
    # COX HACK
    name.upcase == 'CENX' || name.upcase == 'COX'
  end

  def is_sprint?
    name.downcase.include? 'sprint'
  end

  def service_orders
    onovcos = []
    operator_networks.each do |on|
      onovcos += on.service_orders
    end

    return onovcos
  end

  def enni_count
    return enni_news.size
  end

  def path_count
    return paths.size
  end

  def demarc_count
    return demarcs.size
  end

  def ont_count
    return operator_network_types.size
  end

  def contact_count
    return contacts.size
  end

  def short_name
    CenxNameTools::CenxNameHelper.shorten_name(name)
  end

  def generate_id_and_cma
    self.cenx_id = IdTools::CenxIdGenerator.generate_cenx_id(self.class)
    self.cenx_cma = IdTools::CenxCmaGenerator.generate_cenx_cma(self.class)
  end
      
  # KPI methods
  def update_kpi(parent, parent_kpi, kpi_name, kpi_object)
    if parent_kpi == nil
      parent_kpi = get_kpi_mask(kpi_name, kpi_object)
    end
    case kpi_object
    when EnniNew.name, OnNetOvcEndPointEnni.name, BxCosTestVector.name, SpirentCosTestVector.name
      kpi = calculate_kpi(kpi_name, kpi_object, parent_kpi, self)
      # Find all operator networks which have Enni KPIs that don't point to the service provider and only update those
      #ons = operator_networks.joins([:enni_news, :kpis]).where("`kpis`.`id` != ? and `kpis`.`name` = ? and `kpis`.`for_klass` = ? and `kpis`.`actual_kpi` = true", kpi.id, kpi_name, kpi_object)
      ons = operator_networks
      ons.each do |on|
        on.update_kpi(parent, kpi, kpi_name, kpi_object)
      end
    else
      SW_ERR "Invalid kpi_object #{kpi_object} for #{self.class}:#{self.id}"
    end         
  end
  
  def create_default_kpis
    default_kpis = [    
      {:name => "egress_util", :for_klass => EnniNew.name, :warning_time => 80.hours, :error_time => 80.hours, :delta_t => 5.minutes, :warning_threshold => 50, :error_threshold => 75, :units => "%", :actual_kpi => false},
      {:name => "ingress_util", :for_klass => EnniNew.name, :warning_time => 80.hours, :error_time => 80.hours, :delta_t => 5.minutes, :warning_threshold => 50, :error_threshold => 75, :units => "%", :actual_kpi => false},
      
      {:name => "delay", :for_klass => BxCosTestVector.name, :warning_time => 30.minutes, :error_time => 10.minute, :delta_t => 59.seconds, :warning_threshold => nil, :error_threshold => nil, :units => "ms", :actual_kpi => false},
      {:name => "delay_variation", :for_klass => BxCosTestVector.name, :warning_time => 30.minutes, :error_time => 10.minute, :delta_t => 59.seconds, :warning_threshold => nil, :error_threshold => nil, :units => "us", :actual_kpi => false},
      {:name => "flr", :for_klass => BxCosTestVector.name, :warning_time => 30.minutes, :error_time => 10.minute, :delta_t => 59.seconds, :warning_threshold => nil, :error_threshold => nil, :units => "%", :actual_kpi => false},
      
      {:name => "delay", :for_klass => SpirentCosTestVector.name, :warning_time => 30.minutes, :error_time => 10.minute, :delta_t => 5.minutes, :warning_threshold => nil, :error_threshold => nil, :units => "ms", :actual_kpi => false},
      {:name => "delay_variation", :for_klass => SpirentCosTestVector.name, :warning_time => 30.minutes, :error_time => 10.minute, :delta_t => 5.minutes, :warning_threshold => nil, :error_threshold => nil, :units => "us", :actual_kpi => false},
      {:name => "flr", :for_klass => SpirentCosTestVector.name, :warning_time => 30.minutes, :error_time => 10.minute, :delta_t => 5.minutes, :warning_threshold => nil, :error_threshold => nil, :units => "%", :actual_kpi => false}
    ]
    
    cenx_kpis = [    
      {:name => "egress_util", :for_klass => OnNetOvcEndPointEnni.name, :warning_time => 80.hours, :error_time => 80.hours, :delta_t => 5.minutes, :warning_threshold => 50, :error_threshold => 75, :units => "%", :actual_kpi => false},
      {:name => "ingress_util", :for_klass => OnNetOvcEndPointEnni.name, :warning_time => 80.hours, :error_time => 80.hours, :delta_t => 5.minutes, :warning_threshold => 50, :error_threshold => 75, :units => "%", :actual_kpi => false}
    ]

    if is_system_owner?
      default_kpis += cenx_kpis
    end
    
    default_kpis.each {|kpi| kpis << Kpi.create(kpi)}
  end
  
  # If the is_system_owner changes add/remove the KPIs
  def update_kpi_table
    cenx_kpis = [    
      {:name => "egress_util", :for_klass => OnNetOvcEndPointEnni.name, :warning_time => 80.hours, :error_time => 80.hours, :delta_t => 5.minutes, :warning_threshold => 50, :error_threshold => 75, :units => "%", :actual_kpi => false},
      {:name => "ingress_util", :for_klass => OnNetOvcEndPointEnni.name, :warning_time => 80.hours, :error_time => 80.hours, :delta_t => 5.minutes, :warning_threshold => 50, :error_threshold => 75, :units => "%", :actual_kpi => false}
    ]
    if is_system_owner?
      cenx_kpis.each {|kpi| kpis << Kpi.create(kpi)}
    else
      kpis.find_all_by_actual_kpi_and_for_klass(false, OnNetOvcEndPointEnni.name).each {|kpi| kpi.destroy}
    end
  end
  
  private
  
  def valid_cenx_cma?
      valid_cma, error_string = IdTools::CenxCmaGenerator.decode_cenx_cma(self.cenx_cma)
      unless ( valid_cma )
        self.cenx_cma = "Error Generating CMA!"
        errors.add(:cenx_cma, error_string)
        return false
      end
      return true
  end

  def set_path_sphinx_delta_flag
    ReindexSphinx.schedule
  end

end

app/controllers/service_providers_controller.rb
class ServiceProvidersController < ApplicationController
  load_and_authorize_resource
  before_filter do |c| @service_providers_page = true end
  before_filter :find_service_provider, :except => [:index]
  
  # GET /service_providers
  def index
    if @current_user.service_provider.is_system_owner?
      @service_providers = ServiceProvider.all
    else
      @service_providers = [@current_user.service_provider]
    end
  end

  
  def show
    respond_to do |format|
      format.html { render :layout => "application" }
      format.json { render json: @service_provider }
    end
  end

  # GET /service_providers/1/edit
  def edit
  end

  # PUT /service_providers/1
  # PUT /service_providers/1.json
  def update
    respond_to do |format|
      if @service_provider.update_attributes(params[:service_provider])
        if params[:set_default_terms] && can?(:update_all, ServiceProvider)
          # OPTIMIZE ServiceProvider.update_all currently fails with serialized fields
          ServiceProvider.all.each {|sp| sp.update_attributes(:terms => @service_provider.terms)}
        end

        if params[:set_system_logo] && can?(:manage, :customize_system)
          ServiceProvider.set_system_logo(@service_provider)
        end

        format.html { redirect_to service_providers_path, notice: "#{@service_provider.name} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @service_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  
  def find_service_provider
    @service_provider = ServiceProvider.find(params[:id])
  end
    
end

app/views/service_providers/_form.html.haml
=form_for(@service_provider) do |f| 
  -if @service_provider.errors.any?
    #error_explanation
      %a.close{'data-dismiss' => 'alert'} 
        ×
        
      %h2
        =pluralize(@service_provider.errors.count, "error")
        prohibited this 
        = get_term(:service_provider).downcase
        from being saved

      %ul
        -@service_provider.errors.full_messages.each do |msg|
          %li
            =msg
 
  .grid_3.alpha

    %h3.sub_border
      Profile

    %label
      Name
    =f.text_field :name

    %label
      Address
    =f.text_field :address
          
    %label
      Website
    =f.text_field :website
    
    -if can? :manage, :customize_system

      %label
        Set System Logo
      =check_box_tag :set_system_logo, true, @service_provider.is_system_logo


  .grid_6.omega
      
    %h3.sub_border
      Terminology

    .grid_3.alpha
      %label
        Circuit
      =f.text_field :path

      %label
        ENNI
      =f.text_field :enni

      %label
        Network Type
      =f.text_field :network_type  

      %label
        Aggregation Site
      =f.text_field :aggregation_site  

      %label
        Site
      =f.text_field :site

      %label
        Service Provider
      =f.text_field :service_provider       
          
    .grid_3.omega

      %label
        Demarc
      =f.text_field :demarc

      %label
        Site Group
      =f.text_field :site_group

      %label
        Segment
      =f.text_field :segment

      %label
        Core Site
      =f.text_field :wdc

      %label
        Gateway Site
      =f.text_field :gateway_site

      %label
        Off Net
      =f.text_field :microwatt

      %label
        On Net
      =f.text_field :aav


    .clear

    %br
    =f.submit(:value => "Update #{get_term(:service_provider)}", :class => 'submit_button')
    
    -if can? :update_all, ServiceProvider
      &nbsp;
      =f.submit(:name => 'set_default_terms', :value => "Update All #{get_term(:service_provider, true)}", :class => 'submit_button negative', :confirm => "Are you sure you want to overwrite all #{get_term(:service_provider)} terms?")
    
    -if can? :read, User
      or 
      =link_to 'Cancel', users_path
  
.clear
%br

app/views/service_providers/edit.html.haml
-content_for :title do
  CENX - Editing
  =@service_provider.name

.container_12
  .border.clearfix
    .grid_9.alpha
      %h1
        -if can? :read, ServiceProvider
          %a{:href => service_providers_path}
            ="#{get_term(:service_provider)} Info / "
        =@service_provider.name

    .grid_3.align_right.service_provider_logo.omega
      =provider_logo(@service_provider)

.container_12
  .grid_12.alpha.omega
    =render :partial => 'shared/flash_message'

    =render :partial => 'form'

app/views/service_providers/index.html.haml
-content_for :title do
  CENX - 
  = get_term(:service_provider, true)

.container_12
  .border.clearfix
    .grid_9.alpha
      %h1
        ="#{get_term(:service_provider)} Info"

    .grid_3.align_right.service_provider_logo.omega
      =provider_logo(@current_user.service_provider)

.container_12
  .grid_12.alpha.omega
    = render :partial => 'shared/flash_message'

    = render 'shared/table_toggle_link', :title => get_term(:service_provider, true), :table_name => 'service_providers_management'

    %table#service_providers_management.dashboard_table.service_providers_table
      %thead
        %tr
          %th Name
          - if can? :update, ServiceProvider
            %th Users
          %th 

      %tbody
        -@service_providers.each do |sp|
          %tr
            %td
              =link_to sp.name_with_admin_label, service_provider_path(sp)
            - if can? :update, ServiceProvider
              %td
                =sp.users.count           
            %td.align_right.no_wrap
              .button-group.small
                - if can? :read, sp
                  = link_to 'View', service_provider_path(sp), class: 'submit_button icon arrowright', title: "View #{sp.name}"

                - if can? :update, sp
                  = link_to 'Edit', edit_service_provider_path(sp), class: 'submit_button icon edit', :title => "Edit #{sp.name}"    

app/views/service_providers/show.html.haml
-content_for :title do
  CENX - Viewing
  =@service_provider.name

.container_12
  .border.clearfix
    .grid_9.alpha
      %h1
        -if can? :read, ServiceProvider
          %a{:href => service_providers_path}
            ="#{get_term(:service_provider)} Info"
          =" / "
        =@service_provider.name

    .grid_3.align_right.service_provider_logo.omega
      =provider_logo(@service_provider)

.container_12
  .grid_12.alpha.omega
    =render :partial => 'shared/flash_message'

    - if can? :update, @service_provider
      .right
        %a.submit_button.icon.edit{:href => edit_service_provider_path(@service_provider)}
          ="Edit #{@service_provider.name}"

    %form.clearfix

      -@service_provider.operator_networks.group(:operator_network_type_id).each do |on|
        
        -on.get_candidate_ethernet_service_types.each do |est|
          .grid_4
            
            %label
              Service Type
            %p
              =est.name

            %div{:style => 'margin-left: 15px'}
              %label
                Topology
              %p
                =est.segment_types.map{|segment| segment.segment_type}.to_sentence


              %label
                Solution Model
              %p
                =est.demarc_types.where(:name => 'ENNI').map{|d| d.ls_access_solution_model}.to_sentence

            -est.class_of_service_types.each do |cost|

              %label
                CoS
              %p
                =cost.name

              %div{:style => 'margin-left: 15px'}

                %label
                  ="#{get_term(:enni)} Mapping Machanism"
                %p
                  =cost.cos_id_type_enni

                %label
                  ="#{get_term(:enni)} Ingress Mapping"
                %p
                  =cost.cos_mapping_enni_ingress

                %label
                  ="#{get_term(:enni)} Egress Marking"
                %p
                  =cost.cos_marking_enni_egress

                %label
                  ="#{get_term(:enni)} Ingress Rate Limiting "
                %p
                  =cost.bw_profile_types.where(:bwp_type => 'ENNI-INGRESS').map{|bwpt| bwpt.rate_limiting_mechanism }.to_sentence

                %label
                  ENNI Ingress Burst Size
                %p
                  -burst_size = cost.bw_profile_types.where(:bwp_type => 'ENNI-INGRESS').map{|bwpt| bwpt.cbs_range_notes }.to_sentence

                  -if burst_size.present?
                    ="#{burst_size} kB"
                  -else
                    N/A

                %label
                  ENNI Ingress CIR Range 
                %p
                  -burst_size = cost.bw_profile_types.where(:bwp_type => 'ENNI-INGRESS').map{|bwpt| bwpt.cir_range_notes }.to_sentence

                  -if burst_size.present? && burst_size != 'N/A'
                    ="#{burst_size} Mbps"
                  -else
                    N/A                    
                
                %label
                  ="#{get_term(:enni)} Egress Rate Limiting "
                %p
                  =cost.bw_profile_types.where(:bwp_type => 'ENNI-EGRESS').map{|bwpt| bwpt.rate_limiting_mechanism }.to_sentence

                %label
                  ENNI Egress Burst Size 
                %p
                  - burst_size = cost.bw_profile_types.where(:bwp_type => 'ENNI-EGRESS').map{|bwpt| bwpt.cbs_range_notes }.to_sentence

                  -if burst_size.present? && burst_size != 'N/A'
                    ="#{burst_size} kB"
                  -else
                    N/A

                %label
                  ENNI Egress CIR Range 
                %p
                  - burst_size = cost.bw_profile_types.where(:bwp_type => 'ENNI-EGRESS').map{|bwpt| bwpt.cir_range_notes }.to_sentence

                  -if burst_size.present? && burst_size != 'N/A'
                    ="#{burst_size} Mbps"
                  -else
                    N/A  

                %label
                  UNI Mapping Machanism
                %p
                  =cost.cos_id_type_uni

                %label
                  UNI Ingress Mapping 
                %p
                  =cost.cos_mapping_uni_ingress

                %label
                  UNI Egress Marking
                %p
                  =cost.cos_marking_uni_egress

                %label
                  UNI Ingress Rate Limiting 
                %p
                  =cost.bw_profile_types.where(:bwp_type => 'UNI-INGRESS').map{|bwpt| bwpt.rate_limiting_mechanism }.to_sentence
                
                %label
                  UNI Ingress Burst Size 
                %p
                  - burst_size = cost.bw_profile_types.where(:bwp_type => 'UNI-INGRESS').map{|bwpt| bwpt.cbs_range_notes }.to_sentence
                   
                  -if burst_size.present?
                    ="#{burst_size} kB"
                  -else
                    N/A

                %label
                  UNI Ingress CIR Range 
                %p
                  - burst_size = cost.bw_profile_types.where(:bwp_type => 'UNI-INGRESS').map{|bwpt| bwpt.cir_range_notes }.to_sentence
                  
                  -if burst_size.present? && burst_size != 'N/A'
                    ="#{burst_size} Mbps"
                  -else
                    N/A                    

                %label
                  UNI Egress Rate Limiting 
                %p
                  =cost.bw_profile_types.where(:bwp_type => 'UNI-EGRESS').map{|bwpt| bwpt.rate_limiting_mechanism }.to_sentence

                %label
                  UNI Egress Burst Size 
                %p
                  - burst_size = cost.bw_profile_types.where(:bwp_type => 'UNI-EGRESS').map{|bwpt| bwpt.cbs_range_notes }.to_sentence

                  -if burst_size.is_a?(Fixnum)
                    ="#{burst_size} kB"
                  -elsif burst_size.present?
                    =burst_size
                  -else
                    N/A

                %label
                  UNI Egress CIR Range 
                %p
                  - burst_size = cost.bw_profile_types.where(:bwp_type => 'UNI-EGRESS').map{|bwpt| bwpt.cir_range_notes }.to_sentence

                  -if burst_size.present? && burst_size != 'N/A'
                    ="#{burst_size} Mbps"
                  -else
                    N/A  

                %label
                  Availability SLA
                %p
                  ="#{cost.availability}%"

                %label
                  Loss SLA
                %p
                  ="#{cost.frame_loss_ratio}%"

                %label
                  One-Way Delay SLA
                %p
                  -one_way_delay_sla = cost.service_level_guarantee_types.where(:min_dist_km => 0).map{|slgt| slgt.delay_us}.to_sentence
                  -if one_way_delay_sla != 'N/A'
                    ="#{one_way_delay_sla} us"
                  -else
                    =one_way_delay_sla


                %label
                  One-Way Delay Variation SLA
                %p
                  -one_way_delay_variation = cost.service_level_guarantee_types.where(:min_dist_km => 0).map{|slgt| slgt.delay_variation_us}.to_sentence
                  -if one_way_delay_variation != 'N/A'
                    ="#{one_way_delay_variation} us"
                  -else
                    =one_way_delay_variation

                %label
                  MTTR
                %p
                  =cost.mttr_hrs

            -est.demarc_types.where('name <> ?', 'ENNI').each do |dt|
  
              %label
                UNI
              %p
                =dt.name

              %div{:style => 'margin-left: 15px'}
  
                %label
                  Phy
                %p
                  =dt.physical_medium

                %label
                  MTU
                %p
                  =dt.mtu

                %label
                  Device Type
                %p
                  =dt.connected_device_type