config/routes.rb
Sin::Application.routes.draw do

  root :to => 'application#index'

  match '/support' => 'support#index', :as => :support
  match '/logout' => 'sin#logout', :as => :logout
  match '/logo' => 'sin#logo', :as => :logo
  match '/session_expired' => 'sin#session_expired', :as => :session_expired
  match '/login_text' => 'sin#login_text', :as => :login_text

  resources :password_resets, :except => [:index, :destroy]
  resources :roles
  resources :service_providers

  resources :schedules do
    member do
      post   :generate
      get    :reports
      delete :destroy_report
    end
  end  

  resources :settings do
    collection do
      post :update
      get :edit
    end
  end

  resources :users do
    put :set_homepage
    put :toggle_table
    resources :filter_templates, :only => [:create, :update, :destroy]
    resources :site_lists, :only => [:create, :update, :destroy]
  end

  resource :dashboard, :only => [:index] do
    get :index
    get :inventory
    get :ordering
    get :monitoring
    resources :event, :controller => :dashboards, :only => :show do
      collection do
        post :data
      end
    end
  end
  
  resource :report, :only => [:index] do
    get :index    
    get :paths

    get :sla
    get :site_group
    get :satellite_site
    get :cell_site
    get :cell_site_path
    get :metrics
    get :oem_sla
    get :fallout_exception
    get :circuit_utilization
    get :enni_utilization
    
    # required for datatables
    post :sla
    post :site_group
    post :satellite_site
    post :cell_site
    post :cell_site_path
    post :metrics
    post :oem_sla
    post :circuit_utilization
    post :enni_utilization
    post :paths
  end
  
  resources :member_handle_instances do
    collection do
      post :create_or_update
    end
  end

  def standard_component_routes
    member do
      get :ordering
      get :ordering_state
      get :ordering_state_edit
      get :ordering_attributes
      get :ordering_output
      get :ordering_audit
      put :ordering_field_update
      put :provisioning_state_update
      get :monitoring
      get :sm_state
      get :event_history
      get :availability_graph
      get :delay_graph
      get :delay_variation_graph
      get :frame_loss_ratio_graph
      get :troubleshooting_graph
    end
  end

  # Map network on map (agg sites and demarcs)
  resources :network do
    collection do 
      get :demarcs_by_site
    end
  end

  resources :monitoring

  resources :service_orders, :only => [:update]
  match 'service_orders/:id/place_order/:path_id', :to => 'service_orders#place_order', :via => [:post], :as => "place_service_order"
  match 'service_orders/screenshot/:cascade/:order_type/:ts/:num.png', :to => 'service_orders#screenshot', :as => "service_order_screenshot"

  resources :paths do
    standard_component_routes
    member do
      get :list_row
      get :revision
      get :view_data_sources
    end  
  end

  resources :cos_test_vectors do
    member do
      get :availability_graph
      get :delay_graph
      get :delay_variation_graph
      get :frame_loss_ratio_graph
      get :troubleshooting_graph
      get :network_monitoring
    end    
  end

  resources :off_net_ovcs do
    standard_component_routes
    collection do 
      get :map_info_window
      get :map_tooltip
    end
  end

  resources :on_net_ovcs do
    standard_component_routes
    member do
      get :genconfig
      get :site
    end   
    collection do 
      get :map_info_window
      get :map_tooltip
    end     
  end

  resources :nodes do
    member do
      put :provisioning_state_update
    end
    collection do 
      get :nodes
    end
  end

  resources :on_net_routers do
    standard_component_routes
    member do
      get :genconfig
      get :nodes
      get :site
    end   
    collection do 
      get :map_info_window
    end     
  end

  resources :sites do
    member do 
      get :map_info_window
    end
  end

  resources :demarcs do
    standard_component_routes
    collection do 
      get :map_info_window
      get :map_tooltip
    end
  end

  resources :ennis do
    standard_component_routes
    member do
      get :list_row
    end
  end

  resources :off_net_ovc_end_point_unis do
    standard_component_routes
  end

  resources :off_net_ovc_end_point_ennis do
    standard_component_routes
  end

  resources :on_net_ovc_end_point_ennis do
    standard_component_routes
  end

  resources :on_net_router_sub_ifs do
    standard_component_routes
  end

  resources :path_displays do
    member do
      get :monitoring_view
      get :ordering_state_view
      get :inventory_state_view
      get :monitoring_state_view
      get :demarc_view
      get :circuit_path_view
      get :bandwidth_view
      get :technical_contacts_view
      get :summary_view
    end
  end

  resources :enni_displays do
    member do
      get :ordering_state_view
      get :inventory_state_view
      get :monitoring_state_view
      get :technical_contacts_view
    end
  end
  
  resources :state

  # Compare graphs side-by-side
  resources :compares do
    collection do
      delete :clear
      put :reorder
    end
  end


  # Coresite Orders and Tenants
  resources :coresite_orders do
    member do 
      get :change
      put :process_change
      put :accept
      put :update
      put :reject
      put :cancel
      delete :disconnect
      get :_check_available_bandwidth
      get :_view_build_log
    end
    collection do
      get :_check_available_bandwidth_and_vlan
      get :_sites_select
      get :_operator_networks_select
      get :_ennis_select
      get :_phy_type
      get :_access_permission
      get :_provisioned_bandwidth
      get :_next_available_vlan
      get :_service_rates_select
      get :_contact
    end
  end

  resources :custom_application do
    collection do
      get :_locations
      get :_show_add_port
      get :_show_edit_port
      get :_show_delete_port
      get :_nodes_select
      post :_create_port
      put :_update_port
      put :_delete_port
      post :upload_tenants
      get :import_tenants
      get :access_permissions
      put :_update_access_permissions
    end
  end
  
end

app/controllers/coresite_orders_controller.rb
class CoresiteOrdersController < CustomApplicationController

  before_filter :authorize_manage, :except => [:index, :show, :_view_build_log]
  before_filter :init_from_params, :only => [:create, :update, :_check_available_bandwidth_and_vlan]
  before_filter :init_from_model

  def index
    # do not list coresite orders here, now integrated with Dashboard
    redirect_to inventory_dashboard_path
  end

  def show
    @form_action = if @order.can_be_accepted_by_role?(@current_operator_network)
      view_context.accept_coresite_order_path(@order.id)
    else
      view_context.coresite_order_path(@order.id)
    end
  end

  def new
    @order = ServiceOrder.new()
  end

  def update
    @mh = @order.path.member_handle_for_owner_object(@current_user.service_provider)
    unless @mh
      @mh = MemberHandleInstance.new({affected_entity: @order.path, owner: @current_user.service_provider, member_attr: MemberAttr.find_by_affected_entity_type_and_type('Path', 'MemberHandle')})
    end
    @mh.value = params[:order_member_handle]
    respond_to do |format|
      if @mh.save
        format.html { redirect_to coresite_order_path(@order), :notice => 'ID was successfully updated.' }
      else
        flash[:alert] = "ID could not be updated for the following reason: ID #{@mh.errors[:value].join(', ')}"
        show
        format.html { render action: "show" }
      end
    end
  end

  def create

    unless error = can_buyer_access_target?(@buying_operator_network, @target_operator_network)

      order_info = {
        :tenant_a               => @buying_operator_network.id, 
        :nni_a                  => params[:buying_port], 
        :vlan_a                 => params[:buying_vlan], 
        :member_handle_a        => params[:buying_order_member_handle], 
        :tenant_z               => @target_operator_network.id, 
        :cir                    => params[:service_rate].to_i, 
        :requested_service_date => params[:requested_service_date],
        :user                   => @current_user.email
      }.reject{|k, v| v.blank?}

      # To place an order for a XC
      result = CoresiteBuildCenter.new.process_order(order_info, @buying_operator_network.auto_accept?(@target_operator_network))
    end

    respond_to do |format| 
      if error || result[:summary] == 'Failed'
        flash[:alert] = "Order not processed. " + (error ? error : result[:summary_detail])
        new # new method (action)
        format.html { render action: "new" } 
      elsif result[:summary] == 'Fallout'
        flash[:alert] = "Order is in a Fallout state. #{result[:summary_detail]}"
        format.html { redirect_to coresite_order_path(result[:associated_object_id]) } 
      else
        format.html { redirect_to coresite_order_path(result[:associated_object_id]), notice: 'Order was successfully created.' } 
      end
    end

  end

  def change
    if @order.can_be_changed_by_role?(@current_operator_network)
      @form_action = view_context.process_change_coresite_order_path(@order.id)
      @action = :change
    end
  end

  def process_change
    update_order(:change) if @order.can_be_changed_by_role?(@current_operator_network)
  end

  def accept
    if @order.can_be_accepted_by_role?(@current_operator_network)
      update_order(:accept) 
    else
      flash[:alert] = "Order cannot be accepted because order was cancelled by the Buyer."
      respond_to do |format|
        show # include show instance variables
        format.html { render action: "show" } 
      end
    end
  end

  def reject
    if @order.can_be_rejected_by_role?(@current_operator_network)
      update_order(:reject)
    else
      flash[:alert] = "Order cannot be rejected because order was cancelled by the Buyer."
      respond_to do |format|
        show # include show instance variables
        format.html { render action: "show" } 
      end
    end
  end

  def cancel
    if @order.can_be_cancelled_by_role?(@current_operator_network)
      update_order(:cancel) 
    else
      review_action = case @order.order_name.downcase 
      when 'rejected' 
        'rejected'
      when 'delivered'
        'accepted'
      else
        'reviewed'
      end
      flash[:alert] = "Order cannot be cancelled because order has already been #{review_action} by the Target."
      respond_to do |format|
        show # include show instance variables
        format.html { render action: "show" } 
      end
    end

  end

  def destroy
    
    result = if @order.can_be_deleted_by_role?(@current_operator_network)
      CoresiteBuildCenter.new.remove_order({:so_id => @order.id})
    else 
      false
    end

    respond_to do |format|
      if result
        format.html { redirect_to inventory_dashboard_path, notice: 'Order was successfully deleted.' }
      else
        format.html { redirect_to coresite_order_path(@order.id), alert: 'Order cannot be deleted' }
      end
    end

  end

  def disconnect 

    if @order.can_be_disconnected_by_role?(@current_operator_network)
      update_order(:disconnect)
    else 
      flash[:alert] = "Path cannot be disconnected."
      respond_to do |format|
        format.html { redirect_to inventory_dashboard_path }
      end
    end

  end

  def _view_build_log
    build_log = @order.try(:automated_build_logs).try(:first)
    render :partial => 'coresite_shared/build_log', :locals => {build_log: build_log}
  end

  # AJAX Actions

  def _check_available_bandwidth_and_vlan

    if error = can_buyer_access_target?(@buying_operator_network, @target_operator_network)
      message = "<p class='failure'>Cannot check availability. #{error}</p>"

    else
      order_info = {
        :tenant_a               => @buying_operator_network.id, 
        :nni_a                  => (params[:buying_port].blank? ? @order.try(:buying_enni).try(:id) : params[:buying_port]).try(:to_i), 
        :vlan_a                 => params[:buying_vlan], 
        :member_handle_a        => params[:buying_order_member_handle], 
        :tenant_z               => @target_operator_network.id, 
        :nni_z                  => (params[:target_port].blank? ? @order.try(:target_enni).try(:id) : params[:target_port]).try(:to_i), 
        :vlan_z                 => params[:target_vlan], 
        :cir                    => params[:service_rate].to_i, 
        :requested_service_date => params[:requested_service_date],
        :user                   => @current_user.email
      }.reject{|k, v| v.blank?}

      result = CoresiteBuildCenter.new.check_cir_and_vlan(order_info, @buying_operator_network.auto_accept?(@target_operator_network))

      message = if result[:result] == true
        "<p class='success'>Bandwidth and VLAN(s) are available.</p>"
      else
        reason = result[:reason].present? ? result[:reason] : 'Problem reserving bandwith and/or VLAN(s).'
        "<p class='failure'>#{reason}</p>"
      end
    end

    respond_to do |format|
      format.html { render :inline => message }
    end

  end

  def _check_available_bandwidth

    if error = can_buyer_access_target?(@order.buying_operator_network, @order.target_operator_network)
      message = "<p class='failure'>Cannot check bandwidth. #{error}</p>"

    else
      nnis = {}
      nnis[:buyer] = (params[:buying_port].blank? ? @order.try(:buying_enni).try(:id) : params[:buying_port]).try(:to_i)
      nnis[:target] = (params[:target_port].blank? ? @order.try(:target_enni).try(:id) : params[:target_port]).try(:to_i)
      segment = @order.path.segments.first.id
      result = CoresiteBuildCenter.new.check_cirs(segment, nnis, params[:service_rate].to_i)

      message = if result[:result] == true
        "<p class='success'>Bandwidth available.</p>"
      else
        reason = result[:reason].present? ? result[:reason] : 'Problem reserving bandwith and/or VLAN(s).'
        "<p class='failure'>#{reason}</p>"
      end
    end

    respond_to do |format|
      format.html { render :inline => message }
    end

  end

  def _sites_select
    operator_network = OperatorNetwork.find(params[:parent_id])
    if authorized_as_buyer?(operator_network)
      respond_to do |format|
        format.html { render :inline => select_options(operator_network.site.try(:site_group_sites), params[:selected], "id", "name") }
      end
    end
  end

  def _operator_networks_select
    site = Site.find(params[:parent_id])
    buying_operator_network = OperatorNetwork.find(params[:buying_operator_network]) 
    if authorized_as_target?(site) && authorized_as_buyer?(buying_operator_network)
      accessible_operator_networks_with_nnis = site.accessible_operator_networks_by_buying_operator_network(buying_operator_network).reject{ |o| o.live_ennis.count.zero? }
      respond_to do |format|
        format.html { render :inline => select_options(accessible_operator_networks_with_nnis, params[:selected], "id", "tenant_name") }
      end
    end
  end
  
  def _ennis_select
    operator_network = OperatorNetwork.find(params[:parent_id])
    if authorized_as_buyer?(operator_network)
      respond_to do |format|
        format.html { render :inline => select_options(operator_network.try(:enni_news), params[:selected], "id", "port_name") }
      end
    end
  end

  def _phy_type
    if enni = get_enni(params[:parent_id])
      respond_to do |format|
        format.html { render :inline => enni.physical_medium }
      end
    end
  end

  def _provisioned_bandwidth
    if enni = get_enni(params[:parent_id])
      respond_to do |format|
        format.html { render :inline => "#{enni.coresite_provisioned_bandwidth} Mbps"}
      end
    end
  end

  def _service_rates_select
    if enni = get_enni(params[:parent_id])
      respond_to do |format|
        format.html { render :inline => view_context.options_for_select(service_rate_options(enni), params[:selected]) }
      end
    end
  end

  def _contact
    # Operator Network id = Tenant id
    type = params[:type]

app/views/coresite_orders/_display.html.haml
= form_tag(@form_action, :method => "PUT") do
  - order_member_handle = @order.path.member_handle_for_owner_object(@current_user.service_provider).try(:value)

  -# Delete Order by Buyer            
  - if @order.can_be_deleted_by_role?(@current_operator_network)
    .container_12
      .banner.alert
        - order_type, confirm_message = if @order.change_order?
          - ["Change Order", "Are you sure you want to delete this change order? The existing order of #{@order.segment_service_rate} Mbps will not be deleted."]
        - else
          - ["Order", "Are you sure you want to delete this order?"]
        %h2
          = "#{order_type} has been #{@order.order_name}."
        = link_to "Delete #{order_type}", coresite_order_path(@order.id), confirm: confirm_message, method: :delete, :class => 'submit_button activity negative danger blocking', :title => "Delete #{order_type}", 'data-blocking_message' => "<h1>Deleting #{order_type}.</h1><h2>This may take a moment.</h2>"

  .container_12.coresite_form
    .grid_12
      = render :partial => 'shared/flash_message'
    .grid_12
      %h2 
        %strong
          = order_member_handle.blank? ? 'Order' : order_member_handle

      - if (@order.path_id)            
        .view_path
          = link_to "View #{get_term(:path)}", paths_path(:path_details => @order.path_id), :class => 'submit_button activity'

      %table.coresite_table
        %tbody
          %tr
            %td.label State
            %td.states
              %span.state.dot{'class' => "#{@order.order_state_class}"}
              %span.state_text
                = @order.get_order_name

          %td.label Type:
          %td.value
            = @order.action


          - if (@order.path_id)            
            - member_handles = coresite_role ? provider_member_handles(@order.path) : other_provider_member_handles(@order.path)
            - member_handles.each do |member_handle|
              %tr
                %td.label #{member_handle[:label]}:
                %td.value 
                  = member_handle[:value]

  .container_12.coresite_form
    .grid_6.buyer
      %h2 Buyer
      %table.coresite_table
        %tbody
          %tr
            %td.label #{get_term(:site)}:
            %td.value 
              = @order.buying_operator_network.site_name
              %input{:name => 'buying_site', :value => @order.buying_operator_network.try(:site).try(:id), :class => "hidden"}

          %tr
            %td.label #{get_term(:service_provider)}:
            %td.value
              #{@order.buying_operator_network.tenant_name}
              %input{:name => 'buying_operator_network', :value => @order.buying_operator_network.try(:id), :class => "hidden"}

          -# Do not show buying port info to target tenant
          - if coresite_role || @order.buying_role(@current_operator_network)
            %tr
              %td.label #{get_term(:enni)}:
              %td.value 
                = @order.buying_enni.port_names
                %input{:name => 'buying_port', :value =>@order.buying_enni.try(:id), :class => "hidden"}
            %tr
              %td.label Phy Type:
              %td.value #{@order.buying_enni.physical_medium}
            %tr
              %td.label Provisioned Bandwidth:
              %td.value #{@order.buying_enni.coresite_provisioned_bandwidth} Mbps
            %tr
              %td.label VLAN:
              -# TODO: Get VLAN for real
              %td.value 
                = @order.buying_end_point.vlan
                %input{:name => 'buying_vlan', :value => @order.buying_end_point.vlan, :class => "hidden"}


    .grid_6.target
      %h2 Target
      %table.coresite_table
        %tbody
          %tr
            %td.label #{get_term(:site)}:
            %td.value 
              = @order.target_operator_network.site_name
              %input{:name => 'target_site', :value => @order.target_operator_network.try(:site).try(:id), :class => "hidden"}

          %tr
            %td.label #{get_term(:service_provider)}:
            %td.value 
              #{@order.target_operator_network.tenant_name}
              %input{:name => 'target_operator_network', :value => @order.target_operator_network.try(:id), 'data-dependent' => '.target_port', :class => "parent_select target_operator_network_select require hidden"}


          - if target_end_point = @order.target_end_point 
            - if coresite_role || @order.target_role(@current_operator_network)
              -# Do not show target port info to buying tenant          
              %tr
                %td.label #{get_term(:enni)}:
                %td.value 
                  = @order.target_enni.port_names
                  %input{:name => 'target_port', :value => @order.target_enni.try(:id), :class => "hidden"}

              %tr
                %td.label Phy Type:
                %td.value #{@order.target_enni.physical_medium}
              %tr
                %td.label Provisioned Bandwidth:
                %td.value #{@order.target_enni.coresite_provisioned_bandwidth} Mbps
              %tr
                %td.label VLAN:
                %td.value 
                  = target_end_point.vlan
                  %input{:name => 'target_vlan', :value => target_end_point.vlan, :class => "hidden"}

          - elsif @order.can_be_accepted_by_role?(@current_operator_network)
            -# Target is accepting order, instead of Auto Connect
            %tr.input
              %td.label #{get_term(:enni)}*:
              %td.value
                = select_tag "target_port", [], 'data-url' => _ennis_select_coresite_orders_path({:selected => params[:target_port]}), 'data-dependent' => '.target_phy_type_string, .target_provisioned_bandwidth_string', :class => "port target_port parent_select required"
            %tr.input
              %td.label Phy Type:
              %td.value
                .target_phy_type_string{'data-url' => _phy_type_coresite_orders_path}
            %tr.input
              %td.label Provisioned Bandwidth:
              %td.value
                .target_provisioned_bandwidth_string{'data-url' => _provisioned_bandwidth_coresite_orders_path} 
            %tr.input
              %td.label VLAN*:
              %td.value 
                = text_field_tag "target_vlan", params[:target_vlan], :class => "required digits"
                %a.inline_button.choose_next_available_vlan{:href=>'#', 'data-url' => _next_available_vlan_coresite_orders_path} Use next available

  -# Don't allow the following to update member handles: Coresite, during change requests or during Accepting of a Change order
  - unless coresite_role || @action == :change || (@order.can_be_accepted_by_role?(@current_operator_network) && @order.action != 'New')
    .container_12.coresite_form  
      .grid_12
        %h2 #{get_term(:path)}
        %table.coresite_table
          %tbody
            %tr.input
              %td.label #{@current_operator_network.tenant_name}'s ID*:
              %td.value 
                = text_field_tag "order_member_handle", params[:order_member_handle] ? params[:order_member_handle] : order_member_handle, :class => 'path_name required'

  .container_12.coresite_form
    %h2 Requested Service
    .grid_4
      %table.coresite_table
        %tbody
          - if @action == :change
            %tr.input
              %td.label Service Rate*:
              %td.value.input.service_rate
                = select_tag "service_rate", options_for_select(service_rate_options(@order.buying_enni), @order.service_rate), :class => "required"
            %tr.input
              %td.label Requested Service Date:
              %td.value
                - requested_service_date = Date.today
                = requested_service_date.to_formatted_s(:long)
                %input{:name => 'requested_service_date', :value => requested_service_date.to_formatted_s(:requested_service_date), :class => "hidden"}

          - else
            %tr
              %td.label Service Rate:
              %td.value 
                = "#{@order.service_rate} Mbps"
                %input{:name => 'service_rate', :value => @order.service_rate, :class => "hidden"}

            %tr
              %td.label Requested Service Date:
              %td.value 
                = @order.requested_service_date.to_formatted_s(:long)
                %input{:name => 'requested_service_date', :value => @order.requested_service_date.to_formatted_s(:requested_service_date), :class => "hidden"}

          - if @order.can_be_accepted_by_role?(@current_operator_network) || @action == :change
            %tr.input
              %td
                &nbsp;
              %td.value 
                - if @order.can_be_accepted_by_role?(@current_operator_network)
                  - if @order.change_order?
                    %span.submit_button.activity.primary.check_available_bandwidth_and_vlan{'data-url' => _check_available_bandwidth_coresite_order_path(@order.id)} Check Available Bandwidth
                  - else
                    %span.submit_button.activity.primary.check_available_bandwidth_and_vlan{'data-url' => _check_available_bandwidth_and_vlan_coresite_orders_path(@order ? {order_id: @order.id} : {})} Check Available Bandwidth and VLAN
                - elsif @action == :change
                  %span.submit_button.activity.primary.check_available_bandwidth_and_vlan{'data-url' => _check_available_bandwidth_coresite_order_path(@order.id)} Check Available Bandwidth
                .check_available_bandwidth_and_vlan_message


    .grid_8
      %table.coresite_table.col
        %tbody
          %tr
            %td 
              %strong SLA
          %tr
            %td.value
              = render :partial => "sla", :locals => {:buying_operator_network => @order.buying_operator_network}


  - if coresite_role || @order.buying_role(@current_operator_network)
    .container_12.coresite_form
      %h2 Contacts
      .grid_4
        %table.coresite_table
          %tbody
            -# Naming convention at site level
            %tr
              %td Buyer Billing Contact:
            %tr
              %td.value
                = render :partial => 'coresite_shared/contact', :locals => {:contact => @order.buying_operator_network.billing_contact}

      .grid_4
        %table.coresite_table.col
          %tbody
            %tr
              %td Target Engineering Contact:
            %tr
              %td.value
                = render :partial => 'coresite_shared/contact', :locals => {:contact => @order.target_operator_network.engineering_contact}
      .grid_4
        %table.coresite_table.col
          %tbody
            %tr
              %td Coresite Support Contact:
            %tr
              %td.value
                = render :partial => 'coresite_shared/contact', :locals => {:contact => @order.target_operator_network.coresite_contact}


  .container_12
    .action_buttons
      %span#errors_on_form
      %span#messages_on_form

      - if can? :manage, :coresite_order

        - if @action == :change
          - if @order.can_be_changed_by_role?(@current_operator_network)
            %button.submit_button.activity.primary_action.blocking{:type=>'submit', 'data-blocking_message' => '<h1>Order is being processed.</h1><h2>This may take a moment.</h2>'} Submit Order

        - else
          -# Reject Order by Target
          = reject_order_button(@order, @current_operator_network, order_member_handle)
          -# Cancel or Change Order by Buyer            
          = cancel_order_button(@order, @current_operator_network, order_member_handle)
          = change_order_button(@order, @current_operator_network)

          - if @order.can_be_accepted_by_role?(@current_operator_network) 
            -# Accept Order by Target
            %button.submit_button.activity.primary_action.blocking{:type=>'submit', 'data-blocking_message' => "<h1>Accepting Order.</h1><h2>This may take a moment.</h2>"} Accept Order
          - else
            -# Target and Buyer can update (IDs)
            %button.submit_button.activity.blocking{:type=>'submit', 'data-blocking_message' => "<h1>Updating Order.</h1><h2>This may take a moment.</h2>"} Update Order

          -# Disconnect Order by Buyer            
          = disconnect_order_button(@order, @current_operator_network, order_member_handle)


      - if coresite_role
        = link_to 'Back', sub_dashboard_path(@filter_params.merge({:service_provider => @order.buying_operator_network.national_tenant.id})), :class => 'cancel'
      - else
        = link_to 'Back', inventory_dashboard_path, :class => 'cancel'


= form_tag reject_coresite_order_path(@order.id), {:method => "PUT", :class => 'reject_reason'} do
  %h2 Reason for Rejecting Order
  = text_area_tag 'reject_reason',  params[:reject_reason] ? params[:reject_reason] : ''
  .small
    CoreSite is often questioned if connection orders are not approved by their target. Please indicate the reason for rejection. (Optional)

app/views/coresite_orders/_sla.html.haml
- class_of_service_type = OperatorNetwork.coresite_by_site_name(buying_operator_network.site_name).first.operator_network_type.class_of_service_types.first
- service_level_guarantee_type = class_of_service_type.service_level_guarantee_types.first
%ul
  = list_label_and_value 'Availability', class_of_service_type, :availability, format_percentage
  = list_label_and_value 'Frame Loss Ratio', class_of_service_type, :frame_loss_ratio, format_percentage
  = list_label_and_value 'Delay', service_level_guarantee_type, :delay_us, '%s µs'
  = list_label_and_value 'Delay Variation', service_level_guarantee_type, :delay_variation_us, '%s µs'
  = list_label_and_value 'Mean Time to Repair', class_of_service_type, :mttr_hrs, '%s hours'

app/views/coresite_orders/change.html.haml
-content_for :title do
  CoreSite - Order Change

.container_12.page_header
  .border.clearfix
    .grid_9.alpha
      %h1.dashboard_title
        Open Cloud Exchange Order Change

    .grid_3.omega.align_right.service_provider_logo
      = provider_logo(@current_national_tenant)

= render :partial => 'display'

app/views/coresite_orders/new.html.haml
-content_for :title do
  CoreSite - Order New

.container_12.page_header
  .border.clearfix
    .grid_9.alpha
      %h1.dashboard_title
        Open Cloud Exchange New

    .grid_3.omega.align_right.service_provider_logo
      = provider_logo(@current_national_tenant)

#coresite_order_form_new
  = render :partial => 'form', :locals => {:order_new => true}

app/views/coresite_orders/review.html.haml
-content_for :title do
  CoreSite - Order

.container_12.page_header
  .border.clearfix
    .grid_9.alpha
      %h1.dashboard_title
        Open Cloud Exchange Order Accept

    .grid_3.omega.align_right.service_provider_logo
      =provider_logo(@current_user.service_provider)

= render :partial => 'display'

app/views/coresite_orders/show.html.haml
-content_for :title do
  CoreSite - Order

.container_12.page_header
  .border.clearfix
    .grid_9.alpha
      %h1.dashboard_title
        Open Cloud Exchange Order

    .grid_3.omega.align_right.service_provider_logo
      =provider_logo(@current_user.service_provider)

= render :partial => 'display'