config/routes.rb
Sin::Application.routes.draw do

  root :to => 'application#index'

  match '/support' => 'support#index', :as => :support
  match '/logout' => 'sin#logout', :as => :logout
  match '/logo' => 'sin#logo', :as => :logo
  match '/session_expired' => 'sin#session_expired', :as => :session_expired
  match '/login_text' => 'sin#login_text', :as => :login_text

  resources :password_resets, :except => [:index, :destroy]
  resources :roles
  resources :service_providers

  resources :schedules do
    member do
      post   :generate
      get    :reports
      delete :destroy_report
    end
  end  

  resources :settings do
    collection do
      post :update
      get :edit
    end
  end

  resources :users do
    put :set_homepage
    put :toggle_table
    resources :filter_templates, :only => [:create, :update, :destroy]
    resources :site_lists, :only => [:create, :update, :destroy]
  end

  resource :dashboard, :only => [:index] do
    get :index
    get :inventory
    get :ordering
    get :monitoring
    resources :event, :controller => :dashboards, :only => :show do
      collection do
        post :data
      end
    end
  end
  
  resource :report, :only => [:index] do
    get :index    
    get :paths

    get :sla
    get :site_group
    get :satellite_site
    get :cell_site
    get :cell_site_path
    get :metrics
    get :oem_sla
    get :fallout_exception
    get :circuit_utilization
    get :enni_utilization
    
    # required for datatables
    post :sla
    post :site_group
    post :satellite_site
    post :cell_site
    post :cell_site_path
    post :metrics
    post :oem_sla
    post :circuit_utilization
    post :enni_utilization
    post :paths
  end
  
  resources :member_handle_instances do
    collection do
      post :create_or_update
    end
  end

  def standard_component_routes
    member do
      get :ordering
      get :ordering_state
      get :ordering_state_edit
      get :ordering_attributes
      get :ordering_output
      get :ordering_audit
      put :ordering_field_update
      put :provisioning_state_update
      get :monitoring
      get :sm_state
      get :event_history
      get :availability_graph
      get :delay_graph
      get :delay_variation_graph
      get :frame_loss_ratio_graph
      get :troubleshooting_graph
    end
  end

  # Map network on map (agg sites and demarcs)
  resources :network do
    collection do 
      get :demarcs_by_site
    end
  end

  resources :monitoring

  resources :service_orders, :only => [:update]
  match 'service_orders/:id/place_order/:path_id', :to => 'service_orders#place_order', :via => [:post], :as => "place_service_order"
  match 'service_orders/screenshot/:cascade/:order_type/:ts/:num.png', :to => 'service_orders#screenshot', :as => "service_order_screenshot"

  resources :paths do
    standard_component_routes
    member do
      get :list_row
      get :revision
      get :view_data_sources
    end  
  end

  resources :cos_test_vectors do
    member do
      get :availability_graph
      get :delay_graph
      get :delay_variation_graph
      get :frame_loss_ratio_graph
      get :troubleshooting_graph
      get :network_monitoring
    end    
  end

  resources :off_net_ovcs do
    standard_component_routes
    collection do 
      get :map_info_window
      get :map_tooltip
    end
  end

  resources :on_net_ovcs do
    standard_component_routes
    member do
      get :genconfig
      get :site
    end   
    collection do 
      get :map_info_window
      get :map_tooltip
    end     
  end

  resources :nodes do
    member do
      put :provisioning_state_update
    end
    collection do 
      get :nodes
    end
  end

  resources :on_net_routers do
    standard_component_routes
    member do
      get :genconfig
      get :nodes
      get :site
    end   
    collection do 
      get :map_info_window
    end     
  end

  resources :sites do
    member do 
      get :map_info_window
    end
  end

  resources :demarcs do
    standard_component_routes
    collection do 
      get :map_info_window
      get :map_tooltip
    end
  end

  resources :ennis do
    standard_component_routes
    member do
      get :list_row
    end
  end

  resources :off_net_ovc_end_point_unis do
    standard_component_routes
  end

  resources :off_net_ovc_end_point_ennis do
    standard_component_routes
  end

  resources :on_net_ovc_end_point_ennis do
    standard_component_routes
  end

  resources :on_net_router_sub_ifs do
    standard_component_routes
  end

  resources :path_displays do
    member do
      get :monitoring_view
      get :ordering_state_view
      get :inventory_state_view
      get :monitoring_state_view
      get :demarc_view
      get :circuit_path_view
      get :bandwidth_view
      get :technical_contacts_view
      get :summary_view
    end
  end

  resources :enni_displays do
    member do
      get :ordering_state_view
      get :inventory_state_view
      get :monitoring_state_view
      get :technical_contacts_view
    end
  end
  
  resources :state

  # Compare graphs side-by-side
  resources :compares do
    collection do
      delete :clear
      put :reorder
    end
  end


  # Coresite Orders and Tenants
  resources :coresite_orders do
    member do 
      get :change
      put :process_change
      put :accept
      put :update
      put :reject
      put :cancel
      delete :disconnect
      get :_check_available_bandwidth
      get :_view_build_log
    end
    collection do
      get :_check_available_bandwidth_and_vlan
      get :_sites_select
      get :_operator_networks_select
      get :_ennis_select
      get :_phy_type
      get :_access_permission
      get :_provisioned_bandwidth
      get :_next_available_vlan
      get :_service_rates_select
      get :_contact
    end
  end

  resources :custom_application do
    collection do
      get :_locations
      get :_show_add_port
      get :_show_edit_port
      get :_show_delete_port
      get :_nodes_select
      post :_create_port
      put :_update_port
      put :_delete_port
      post :upload_tenants
      get :import_tenants
      get :access_permissions
      put :_update_access_permissions
    end
  end
  
end

app/controllers/reports_controller.rb
class ReportsController < CustomApplicationController
  include PathsHelper
  include DashboardHelper
  before_filter :common_rollup_report, :only => [:site_group, :satellite_site, :cell_site, :cell_site_path, :metrics]
  before_filter :common_fallout_exception_report, :only => [:fallout_exception]
  before_filter :set_common_params

  def index
    if can? :read, :sla_reports
      redirect_to sla_report_path(preferred_mode(:monitoring))
    elsif can? :read, :inventory_exception_reports
      redirect_to fallout_exception_report_path({:fallout_exception_type => 'audit'}.merge(preferred_mode(:inventory)))
    elsif can? :read, :ordering_exception_reports
      redirect_to fallout_exception_report_path({:fallout_exception_type => 'ordering'}.merge(preferred_mode(:ordering)))
    elsif can? :read, :rolled_up_reports
      redirect_to site_group_report_path(preferred_mode(:monitoring))
    elsif can? :read, :circuit_utilization_reports
      redirect_to circuit_utilization_report_path(preferred_mode(:monitoring))
    elsif can? :read, :enni_utilization_reports
      redirect_to enni_utilization_report_path(preferred_mode(:ordering))
    elsif can? :manage, Schedule
      redirect_to schedules_path
    end
  end
  
  def paths
    authorize! :read, :sla_reports

    @paths = @paths.s_unique
    @sites = SinPathServiceProviderSphinx.select('path_id AS id, member_handle').
                                where('member_handle LIKE ?', "%#{params[:term]}%").
                                where('path_id IN (?)', @paths.pluck('paths.id')).
                                where('service_provider_id = ?', @current_user.service_provider.id).
                                limit(20)

    sites_hash = {}
    @sites.map {|site| sites_hash[site[:id]] = site[:member_handle]}

    respond_to do |format|
      format.json { render :json => sites_hash }
    end
  end

  def site_group
    authorize! :read, :rolled_up_reports
    @exceptions = site_group_exceptions(@paths, params, @date_range_start, @date_range_end, @current_user)

    if request.format.json?
      @total = @exceptions.s_count
    else
      @cell_sites = cell_site_exceptions(@paths, params, @date_range_start, @date_range_end, @current_user)
      get_severity_counts(@cell_sites)    
    end

    report_response!        
  end

  def satellite_site
    authorize! :read, :rolled_up_reports
    @exceptions = satellite_site_exceptions(@paths, params, @date_range_start, @date_range_end, @current_user)

    if request.format.json?
      @total = @exceptions.s_count
    else
      @cell_sites = cell_site_exceptions(@paths, params, @date_range_start, @date_range_end, @current_user)
      get_severity_counts(@cell_sites)    
    end

    report_response!    
  end

  def cell_site
    authorize! :read, :rolled_up_reports
    @exceptions = cell_site_exceptions(@paths, params, @date_range_start, @date_range_end, @current_user)
    get_severity_counts(@exceptions)    

    report_response!
  end

  def cell_site_path
    authorize! :read, :rolled_up_reports
    @metrics_report = true  
    @exceptions = cell_site_path_exceptions(@paths, params, @date_range_start, @date_range_end, @current_user)
    get_severity_counts(@exceptions)

    report_response!
  end

  def metrics
    authorize! :read, :rolled_up_reports
    @metrics_report = true
    @exceptions = metrics_exceptions(@paths, params, @date_range_start, @date_range_end, @current_user)
    get_severity_counts(@exceptions)

    report_response!
  end

  def sla
    authorize! :read, :sla_reports
    @exceptions = sla_exceptions(@paths, params, @date_range_start, @date_range_end, @current_user)    
    get_severity_counts(@exceptions)    

    report_response!
  end

  def oem_sla
    authorize! :read, :oem_reports
        
    # TODO: move hardcoded values elsewhere
    @flr_major = 10.0
    @flr_minor = 5.0
    @fd_major = 30.0
    @fd_minor = 15.0
    @fdv_major = 2500.0
    @fdv_minor = 1000.0

    @paths = @paths.s_unique
    @exceptions = oem_sla_exceptions(@paths, params, @date_range_start, @date_range_end, @current_user)    
    unless request.format.json?
      @minor = @exceptions.s_minor.s_count
      @major = @exceptions.s_major.s_count
      @critical = @exceptions.s_critical.s_count
      @total = @minor + @major + @critical      
    end

    report_response!
  end


  def fallout_exception
    if ['ordering', 'audit'].include?(params[:fallout_exception_type]) && params[:fallout_exception_type] == 'ordering' 
      authorize! :read, :ordering_exception_reports
    else
      authorize! :read, :inventory_exception_reports
    end

    if App.is?(:coresite)
      @fallout_build = @paths.s_fallout_build.s_date_range(@date_range_start, @date_range_end).count('paths.id', :distinct => true)
    end

    # @fallout_categories = @paths.s_fallout_category_counts.s_date_range(@date_range_start, @date_range_end)

    # Allow user to search by Path ID
    path_ids = fulltext_search

    # do a big giant IN if sphinx was used to filter results
    @paths = @paths.where(:paths => {:id => path_ids}) unless path_ids.nil?

    @paths = @paths.s_unique    

    # Get All exceptions not just current one
    @exceptions = fallout_exceptions(@paths, params, @date_range_start, @date_range_end, @current_user)

    # a path can have multiple exceptions so this scope does not behave as we would like
    # @fallout_categories = @exceptions.collect { |e| e.category }.inject(Hash.new(0)) { |hash, item| item = "Other" if item.nil?; hash[item] += 1; hash }
    @fallout_categories = @exceptions.select('fallout_exceptions.category as fallout_category, count(*) as fallout_category_count').group('fallout_exceptions.category')

    report_response!
  end


  def circuit_utilization
    authorize! :read, :circuit_utilization_reports
    
    @paths = @paths.s_unique
    @exceptions = circuit_utilization_exceptions(@paths, params, @date_range_start, @date_range_end, @current_user)
    
    # TODO: Limit the rows returns
    @top_talkers = TopTalkerCosEndPoint.includes([:cos_end_point => {:segment_end_point => [:demarc, {:segment => :paths}]}]).
                                        where('paths.id in (:path_ids)', {:path_ids => @paths.pluck('paths.id')}).
                                        group('cos_end_point_id, direction')
    
    unless request.format.json?
      @minor = @exceptions.s_minor.s_count
      @major = @exceptions.s_major.s_count
      @critical = @exceptions.s_critical.s_count
      @total = @minor + @major + @critical      
    end

    report_response!                                        
  end


  def enni_utilization
    authorize! :read, :enni_utilization_reports
    require 'will_paginate/array'
    @exceptions = []      
    @ennis = @ennis.s_unique
    @ennis = @ennis.includes([:segment_end_points])
              
    if params[:js_data] == 'provisioned_bandwidth'
      sort_columns = [nil, 'sites.name', nil, nil, nil, 'cir_limit', 'eir_limit']
      sort_column = sort_columns[params[:iSortCol_0].to_i || 2]
      sort_direction = params[:sSortDir_0] || "DESC"
      
      @ennis = @ennis.order("#{sort_column} #{sort_direction}")

      unless request.format.csv? || request.format.pdf?
        @ennis = @ennis.paginate(:page => @current_page, :per_page => params[:iDisplayLength])
      end
    else
      @exceptions = enni_utilization_exceptions(@ennis, params, @date_range_start, @date_range_end, @current_user)
             
      unless request.format.json?
        @minor = @exceptions.s_minor.s_count
        @major = @exceptions.s_major.s_count
        @critical = @exceptions.s_critical.s_count
        @total = @minor + @major + @critical      
      end
                        
      # TODO: Limit the rows returns
      @top_talkers = TopTalkerEnni.includes(:enni_new).
                                    where('enni_id in (:enni_ids)', {:enni_ids => @ennis.pluck('demarcs.id').uniq}).
                                    group('enni_id, direction')                                     
    end
    
    report_response!           
  end
  

  protected

  def preferred_mode(mode)
    can?(:read, mode.to_sym)? {:mode => mode} : {}
  end

  def set_default_date_range
    @default_date_range = @rollup_report ? 'seven_days_previous' : 'month_to_date'
  end

  def set_common_params
    @params = request.GET
    @default_date_range = 'month_to_date' if @default_date_range.nil?
    @date_range_start, @date_range_end = get_date_range(params['date_range_selector'], params['date_range_start'], params['date_range_end'], @default_date_range ? @default_date_range : 'month_to_date')
    @reports_page = true
    @date_range_select = true
    @component_condition = params[:component_condition] || 'and'
    @filter_template = FilterTemplate.new
    @site_list = SiteList.new
    @current_page = (params[:iDisplayStart].to_i/params[:iDisplayLength].to_i rescue 0)+1
    @site = Site.find(params[:site]) if params[:site].present?
    @site_group = SiteGroup.find(params[:site_group]) if params[:site_group].present?
    @demarc = Demarc.find(params[:demarc]) if params[:demarc].present?
  end
  
  def common_rollup_report
    @rollup_report = true
    @default_date_range = 'week_to_date'
  end

  def common_fallout_exception_report
    @default_date_range = 'seven_days_previous'
  end

  def get_severity_counts(exceptions)
    unless request.format.json?
      @counts = exceptions.s_severity_count    
      @clear = @counts.find {|k| k['severity'] == 'clear'}.try(:[], :count) || 0
      @minor = @counts.find {|k| k['severity'] == 'minor'}.try(:[], :count) || 0
      @major = @counts.find {|k| k['severity'] == 'major'}.try(:[], :count) || 0
      @critical = @counts.find {|k| k['severity'] == 'critical'}.try(:[], :count) || 0
      @total = @clear + @minor + @major + @critical
    else
      @total = @exceptions.s_count
    end
  end

  def report_response!

app/views/reports/_rolled_up_severity.html.haml
- if exception.severity == 'clear'
  .dashboard_legend_box.monitoring{:class => "ok help_on_hover", :title => "All metrics OK"}
    i
- elsif exception.severity == 'minor'
  .dashboard_legend_box.monitoring{:class => "warning help_on_hover", :title => "Metrics on one protection path out of spec"}
    i
- elsif exception.severity == 'major'
  .dashboard_legend_box.monitoring{:class => "failed help_on_hover", :title => "Metrics on both protection paths out of spec"}
    i                

app/views/reports/_sla_circuit_link.html.haml
-"#{get_term(:path)}:"
-path_mh = member_handle_for_current_user(path, @current_user)
%a{:href => paths_path(@params.merge({:path_details => path.id, :entity_id => exception.cos_test_vector.cos_end_point.segment_end_point.id, :entity_type => exception.cos_test_vector.cos_end_point.segment_end_point.class, :tab_id => exception.cos_test_vector.cos_end_point.id, :section_id => exception.cos_test_vector.id, :graph_type => exception.to_internal_metric_type.to_s, :date_range_start => Time.at(exception.time_declared_epoch.to_i).in_time_zone.beginning_of_month.strftime(RangeDate::DATE_FORMAT), :date_range_end => Time.at(exception.time_declared_epoch.to_i).in_time_zone.end_of_month.strftime(RangeDate::DATE_FORMAT)})), :title => "See #{get_term(:path)} List for #{path_mh}", :target => '_blank'}
  =truncate path_mh
%br
Component:
%br
-if exception.cos_test_vector.is_a?(SpirentCosTestVector)
  -cos_mh = exception.cos_test_vector.circuit_id
-else
  -cos_mh = member_handle_for_current_user(exception.cos_test_vector.cos_end_point.segment_end_point, @current_user)
%a{:href => paths_path(@params.merge({:path_details => path.id, :entity_id => exception.cos_test_vector.cos_end_point.segment_end_point.id, :entity_type => exception.cos_test_vector.cos_end_point.segment_end_point.class, :tab_id => exception.cos_test_vector.cos_end_point.id, :section_id => exception.cos_test_vector.id, :graph_type => exception.to_internal_metric_type.to_s, :date_range_start => Time.at(exception.time_declared_epoch.to_i).in_time_zone.beginning_of_month.strftime(RangeDate::DATE_FORMAT), :date_range_end => Time.at(exception.time_declared_epoch.to_i).in_time_zone.end_of_month.strftime(RangeDate::DATE_FORMAT)})), :title => "See #{get_term(:path)} List for #{cos_mh}", :target => '_blank'}
  =cos_mh

app/views/reports/_utilization_severity.html.haml
- if exception.severity == :minor
  .dashboard_legend_box.monitoring{:class => "dependency help_on_hover", :title => "Measured Utilization above minor threshold for more than allowed time during calendar month"}
    i
- elsif exception.severity == :major
  .dashboard_legend_box.monitoring{:class => "warning help_on_hover", :title => "Measured Utilization above major threshold for more than allowed time during calendar month"}
    i

app/views/reports/cell_site_path_exceptions.pdf.haml
.container_12
  .border.clearfix
    .grid_9.alpha
      %h1
        ="#{get_term(:demarc)} Path Level Report"

    .grid_3.align_right.service_provider_logo.omega
      =provider_logo(@current_user.service_provider, pdf=true)


.container_12.clearfix

  .grid_4.alpha
    =render '/reports/rolled_up_interactive_pie.html.haml', :current_path => 'cell_site_path_report_path', :title => get_term(:path), :pdf => true

  .grid_8.omega
    =render '/reports/filter.html.haml'
      
.container_12
      
  .grid_12{:class => 'alpha omega'}     
  
    %h3.inline
      Protection Paths
  
    %table#site_groups.dashboard_table.exceptions
      %thead
        %tr
          %th Sev
          %th Analysis Period
          %th 
            ="#{get_term(:demarc)}"
          %th Role
          %th 
            ="#{get_term(:aggregation_site)}"
          %th Metrics Count
          %th OK Metrics
          %th Minor Metrics
          %th Major Metrics
                                                  
      %tbody
        -@exceptions.each do |exception|
          %tr
            %td
              =exception.severity.to_s.titleize
            %td
              =exception.weekly_period
            %td
              =member_handle_for_current_user(exception.demarc, @current_user)
            %td
              =exception.role
            %td
              =exception.site.name
            %td
              =exception.metric_count
            %td
              ="#{exception.metric_percentage(exception.metric_ok_count)}%"
            %td
              ="#{exception.metric_percentage(exception.metric_minor_count)}%"
            %td
              ="#{exception.metric_percentage(exception.metric_major_count)}%"

app/views/reports/circuit_utilization_exceptions.js.erb
<%- rows = [] -%>
<%- @exceptions.each do |exception| -%>
  <%- exception.cos_end_point.segment_end_point.ovc.paths.each do |evc| -%>

    <%- severity = render :partial => "utilization_severity", :locals => {:exception => exception} -%>
    <%- circuit_link = render :partial => "circuit_utilization_link", :locals => {:exception => exception, :evc => evc} -%>
    <%- info_bubble = render :partial => "circuit_utilization_info_bubble", :locals => {:exception => exception} -%>

    <%- rows << [ severity,
                  circuit_link,
                  timestamp_to_date_time(exception.time_declared),
                  evc.on_net_ovcs.collect{|segment| segment.site.name}.join(', '),
                  exception.cos_end_point.segment_end_point.segment.service_provider.name,
                  exception.direction.to_s.titleize,
                  exception.cos_end_point.cos_instance.cos_name,
                  info_bubble ] -%>

  <%- end -%>                  
<%- end -%>

{
    "sEcho": <%= params[:sEcho] -%>,
    "iTotalRecords": <%= @exceptions.count -%>,
    "iTotalDisplayRecords": <%= @exceptions.count -%>,
    "aaData": <%= raw(rows) -%>
}

app/views/reports/enni_utilization_provisioned_bandwidth.js.erb
<%- rows = [] -%>
<%- @ennis.each do |enni| -%>
  <%- pb = enni.get_provisioned_bandwidth -%>
  <%- circuit_link = render :partial => "provisioned_bandwidth_link", :locals => {:enni => enni} -%>

  <%- rows << [ circuit_link,
                enni.site.name,
                enni.rate,
                number_with_precision(pb[:grand][:cir_rate], :precision => 3, :strip_insignificant_zeros => true),
                number_with_precision(pb[:grand][:eir_rate], :precision => 3, :strip_insignificant_zeros => true),
                number_with_precision(enni.cir_limit, :precision => 3, :strip_insignificant_zeros => true),
                number_with_precision(enni.eir_limit, :precision => 3, :strip_insignificant_zeros => true) ] -%>
<%- end -%>

{
    "sEcho": <%= params[:sEcho] -%>,
    "iTotalRecords": <%= @ennis.length > 0 ? @ennis.total_entries : 0 -%>,
    "iTotalDisplayRecords": <%= @ennis.length > 0 ? @ennis.total_entries : 0 -%>,
    "aaData": <%= raw(rows) -%>
}

app/views/reports/fallout_exception.html.haml
- fallout_data = ApplicationHelper::AUDIT_FALLOUT_TYPES[params[:fallout_exception_type]]
-content_for :title do
  = "CENX - #{fallout_data[:name]} Report"


.container_12
  .border.clearfix
    .grid_9.alpha
      %h1
        = "#{fallout_data[:name]} Report"

    .grid_3.align_right.service_provider_logo.omega
      =provider_logo(@current_user.service_provider)


.container_12.clearfix

  =render 'shared/flash_message'
  
  .grid_4
    =render 'fallout_exception_interactive_pie', :current_path => 'fallout_exception_report_path'

  .grid_5
    =render "shared/search_form_wide", :hide_severity => true, :show_fallout_category => true, :show_cascade_id => true, :default_period => 'Previous 12 months', :hide_site_list => true

  .grid_3
    =render 'filter_form', :report_type => 'inventory_exception'


.container_12
      
  .grid_12{:class => 'alpha omega'}
    
    .right
      / %a.submit_button{:href => fallout_exception_report_path(@filter_params.merge({:pdf_data => 'exceptions', :format => :pdf})), :target => '_blank'}
      /   Export PDF   
      / %a.submit_button{:href => fallout_exception_report_path(@filter_params.merge({:csv_data => 'exceptions', :format => :csv})), :target => '_blank'}
      /   Export All CSV     
      %a.submit_button{:href => fallout_exception_report_path(@filter_params.merge({:xlsx_data => 'exceptions', :format => :xlsx})), :target => '_blank'}
        Export All XLSX     

    = render 'shared/table_toggle_link', :title => "Exceptions", :table_name => 'sla_exceptions'      
  
    %table#fallout_exceptions.dashboard_table.exceptions{'data-src' => fallout_exception_report_path(@filter_params.merge({:js_data => 'exceptions'}))}
      %thead
        %tr
          %th= get_term(:cascade)
          %th Date
          %th
            = get_term(:aggregation_site)
          %th 
            = get_term(:service_provider)
          %th Category
          %th Details
                                                  
      %tbody

app/views/reports/fallout_exception_exceptions.js.erb
<%- rows = [] -%>
<%- @exceptions.each do |exception| -%>

  <%- path = exception.path -%>
  <%- category = exception.category.blank? ? exception.exception_type : exception.category -%>

  <%- circuit_link = render :partial => "fallout_exception_circuit_link", :locals => {:exception => exception, :path => path} -%>

  <%- rows << [ circuit_link,
                timestamp_to_date(exception.time),
                path.site_names,
                path.aav,
                category,
                exception.details.gsub(/,/,"<br />").gsub(/;/,"; ") ] -%>

<%- end -%>

{
    "sEcho": <%= params[:sEcho] -%>,
    "iTotalRecords": <%= @exceptions.count -%>,
    "iTotalDisplayRecords": <%= @exceptions.count -%>,
    "aaData": <%= raw(rows) -%>
}

app/views/reports/fallout_exception_exceptions.old.csv.erb
<%- headers = ["Cascade ID", "Date", get_term(:aggregation_site), get_term(:service_provider), "Exception Type", "Details"] -%>
<%= CSV.generate_line headers -%>
<%- exceptions.each_with_index do |exception, i| -%>
<%- path = exception.path -%>
<%- row = [path.cascade_id,
           Time.at(exception.timestamp).utc.strftime('%Y-%m-%d %H:%M:%S'),
           path.site_names,
           path.aav,
           exception.exception_type,
           exception.details] -%>

<%= CSV.generate_line(row).html_safe -%>
<%- end -%>
<%= render '/reports/filter.csv.erb' -%>

app/views/reports/oem_sla_report.csv.erb
<%- headers = ["Report Name", "FLR Daily Avg PAS", "FD Daily Avg PAS", "FDR Daily Avg PAS", "FLR Daily Avg", "FD Daily Avg", "FDR Daily Avg", "Availability Daily Avg"] -%>
<%= CSV.generate_line headers -%>
<%- row = [] -%>
<%= CSV.generate_line(row).html_safe -%>
<%= render '/reports/filter.csv.erb' -%>

app/views/reports/site_group_exceptions.js.erb
<%- rows = [] -%>
<%- @exceptions.each do |exception| -%>

  <%- rows << [ exception.weekly_period,
                link_to(exception.site_group.name, satellite_site_report_path(@filter_params.merge({:site_group => exception.site_group_id, :severity => ''}))),
                link_to(exception.site_count, satellite_site_report_path(@filter_params.merge({:site_group => exception.site_group_id, :severity => ''}))),
                link_to(exception.demarc_count, cell_site_report_path(@filter_params.merge({:site_group => exception.site_group_id, :severity => ''}))),
                "#{exception.demarc_percentage(exception.demarc_ok_count)}%",
                "#{exception.demarc_percentage(exception.demarc_minor_count)}%",
                "#{exception.demarc_percentage(exception.demarc_major_count)}%"
                 ] -%>

<%- end -%>

{
    "sEcho": <%= params[:sEcho] -%>,
    "iTotalRecords": <%= @total -%>,
    "iTotalDisplayRecords": <%= @total -%>,
    "aaData": <%= raw(rows) -%>
}